In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from transformers import (
    BertTokenizer,
    BertForMaskedLM,
    BertConfig,
    LineByLineTextDataset,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments
)
import torch
from sklearn.model_selection import train_test_split
from typing import Literal
from torch import nn
from transformers import BertModel,AutoModel
from huggingface_hub import hf_hub_download
from typing import Literal
import json

c:\Users\ritik\anaconda3\envs\datascience310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
nbs_ = pd.read_csv('E:\\GitHub\\Multi-Model-Bias-Detection-and-Debiasing-the-News\\EDA\\No_Corrupted_NBS.csv')

In [3]:
nbs_

,unique_id,outlet_x,title,content,image_description_x,text_label_x,multimodal_label_x,outlet_y,headline,top_image,article_text,new_categories,news_categories_confidence_scores,text_label_y,multimodal_label_y,image_description_y,image_filename,image_path
0,23400064a2,CBC.ca,Anishnabeg Outreach develops self-serve mental...,A new resource developed by Anishnabeg Outreac...,The image shows a person standing in front of ...,Unlikely,Likely,CBC.ca,Anishnabeg Outreach develops self-serve mental...,"{'bytes': None, 'path': '/projects/NMB-Plus/ra...",A new resource developed by Anishnabeg Outreac...,['Health' 'Local/Regional'],[0.85 0.75],Unlikely,Likely,The image shows a person standing in front of ...,23400064a2.jpeg,C:\Users\ritik\Downloads\images\images\2340006...
1,0bad329c25,CBC.ca,South Asian newcomers to Canada say online hat...,International student Miran Kadri had many thi...,Two individuals with backpacks walking on a ci...,Likely,Unlikely,CBC.ca,South Asian newcomers to Canada say online hat...,"{'bytes': None, 'path': '/projects/NMB-Plus/ra...",International student Miran Kadri had many thi...,['National' 'Opinion/Editorial'],[0.85 0.65],Likely,Unlikely,Two individuals with backpacks walking on a ci...,0bad329c25.jpeg,C:\Users\ritik\Downloads\images\images\0bad329...
2,267f8bc361,CBC.ca,Program that pairs nurses with RCMP on mental ...,A program in Fort McMurray that pairs police o...,A smiling woman in a pink shirt is seated in a...,Unlikely,Likely,CBC.ca,Program that pairs nurses with RCMP on mental ...,"{'bytes': None, 'path': '/projects/NMB-Plus/ra...",A program in Fort McMurray that pairs police o...,['Local/Regional' 'Health'],[0.85 0.75],Unlikely,Likely,A smiling woman in a pink shirt is seated in a...,267f8bc361.jpeg,C:\Users\ritik\Downloads\images\images\267f8bc...
3,2fab02aa42,CBC.ca,Should social media come with a health warning...,The U.S. surgeon general has called for social...,"A person is holding a smartphone, possibly rea...",Likely,Unlikely,CBC.ca,Should social media come with a health warning...,"{'bytes': None, 'path': '/projects/NMB-Plus/ra...",The U.S. surgeon general has called for social...,['Health' 'Opinion/Editorial'],[0.9 0.7],Likely,Unlikely,"A person is holding a smartphone, possibly rea...",2fab02aa42.jpeg,C:\Users\ritik\Downloads\images\images\2fab02a...
4,004798d706,CBC.ca,Inside Out 2: What the movie’s 4 new emotions ...,"Emotions are clues about ourselves, says exper...",A character with blue hair and a green dress s...,Likely,Unlikely,CBC.ca,Inside Out 2: What the movie’s 4 new emotions ...,"{'bytes': None, 'path': '/projects/NMB-Plus/ra...","Emotions are clues about ourselves, says exper...",['Entertainment' 'Health'],[0.85 0.75],Likely,Unlikely,A character with blue hair and a green dress s...,004798d706.jpeg,C:\Users\ritik\Downloads\images\images\004798d...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6244,0471e108dd,CNN,Opinion: We Germans are making Trump ‘thunders...,Editor’s Note: Anna Sauerbrey is the foreign e...,A black and white photo of a large assembly ha...,Likely,Likely,CNN,Opinion: We Germans are making Trump ‘thunders...,"{'bytes': None, 'path': '/projects/NMB-Plus/wh...",Editor’s Note: Anna Sauerbrey is the foreign e...,['Opinion/Editorial' 'Politics'],[0.9 0.8],Likely,Likely,A black and white photo of a large assembly ha...,0471e108dd.jpg,C:\Users\ritik\Downloads\images\images\0471e10...
6245,1e9e145f6e,CNN,Brazil’s floods smashed through barriers desig...,Karine Pitana had just paid off the last insta...,An aerial view of a flooded road with a yellow...,Likely,Likely,CNN,Brazil’s floods smashed through barriers desig...,"{'bytes': None, 'path': '/projects/NMB-Plus/wh...",Karine Pitana had just paid off the last insta...,['Local/Regional' 'National'],[0.85 0.75],Likely,Likely,An aerial view of a flooded road with a yellow...,1e9e145f6e.jpg,C:\Users\ritik\Downloads\images\images\1e9e145...
6246,0bc2d5dd25,CNN,"In a city cut off from the world, guns and dru...",On the rare days that the hills surrounding Po...,An individual stands in a barren landscape wit...,Likely,Likely,CNN,"In a city cut off from the world, guns and dru...","{'bytes': None, 'path': '/projects/NMB-Plus/wh...",On the rare days that the hills surrounding Po...,['National' 'International'],[0.8 0.7],Likely,Likely,An individual stands in a barren landscape wit...,0bc2d5dd25.jpg,C:\Users\ritik\Downloads\images\images\0bc2d5d...
6247,1913a7c1b2,CNN,Switzerland wins Eurovision after politically ...,Switzerland’s Nemo won a chaotic and political...,A person in a fluffy red and white costume wit...,Likely,Likely,CNN,Switzerland wins Eurovision after politically ...,"{'bytes': None, 'path': '/projects/NMB-Plus/wh...",Switzerland’s Nemo won a chaotic and political...,['International' 'Entertainment'],[0.85 0.8 ],Likely,Likely,A person in a fluffy red and white costume wit...,1913a7c1b2.jpg,C:\Users\ritik\Downloads\images\images\1913a7c...
6248,075600b516,CNN,"May 9, 2024 Israel-Hamas war - CNN",Netanyahu says Biden made a mistake in delayin...,An armored military vehicle with a mounted gun...,Likely,Likely,CNN,"May 9, 2024 Israel-Hamas war - CNN","{'bytes': None, 'path': '/projects/NMB-Plus/wh...",Netanyahu says Biden made a mistake in delayin...,['Politics' 'International'],[0.95 0.9 ],Likely,Likely,An armored military vehicle with a mounted gun...,075600b516.jpg,C:\Users\ritik\Downloads\images\images\075600b...

In [4]:
nbs_['text_labels']=nbs_['text_label_x'].apply(lambda x : 'biased' if x=='Likely' else 'non-biased')

In [5]:
nbs_['MultiModal_Label'] =nbs_['multimodal_label_x']
nbs_=nbs_.drop(columns=['multimodal_label_x','multimodal_label_y'])

In [6]:
nbs_['caption']=nbs_['image_description_x']
nbs_=nbs_.drop(columns=['image_description_x','image_description_y'])

In [7]:
'''Removing non words '''

nbs_['article_text'] = nbs_['article_text'].replace(to_replace=r'[^\w\s]', value='', regex=True)
nbs_['caption'] = nbs_['caption'].replace(to_replace=r'[^\w\s]', value='', regex=True)

'''Lower casing the text'''

nbs_ = nbs_.applymap(lambda x: x.lower() if isinstance(x, str) else x)

C:\Users\ritik\AppData\Local\Temp\ipykernel_11128\4013432535.py:8: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  nbs_ = nbs_.applymap(lambda x: x.lower() if isinstance(x, str) else x)

In [8]:
nbs_['MultiModal_Label']=nbs_['MultiModal_Label'].apply(lambda x : 'biased' if x=='Likely' else 'non-biased')

In [9]:
nbs_['MultiModal_Label'] = nbs_['MultiModal_Label'].apply(lambda x: 1 if x == 'biased' else 0)

In [10]:
nbs_ = nbs_.iloc[5000:]

In [11]:
nbs_babe=nbs_[['headline','article_text','MultiModal_Label']]
nbs_babe.rename(columns={
    'article_text': 'article',
    'headline': 'text',
    'MultiModal_Label': 'label_bias' 
},inplace=True)
nbs_babe.columns

C:\Users\ritik\AppData\Local\Temp\ipykernel_11128\3516275186.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nbs_babe.rename(columns={

Index(['text', 'article', 'label_bias'], dtype='object')

In [12]:
nbs_nbs = nbs_[['caption','image_path','MultiModal_Label']]
nbs_nbs.rename(columns={
    'caption': 'article_text',
    'image_path': 'image_path',
    'MultiModal_Label': 'MultiModal_Label' 
},inplace = True)

C:\Users\ritik\AppData\Local\Temp\ipykernel_11128\3631541205.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nbs_nbs.rename(columns={

In [13]:
nbs_.columns

Index(['unique_id', 'outlet_x', 'title', 'content', 'text_label_x', 'outlet_y',
       'headline', 'top_image', 'article_text', 'new_categories',
       'news_categories_confidence_scores', 'text_label_y', 'image_filename',
       'image_path', 'text_labels', 'MultiModal_Label', 'caption'],
      dtype='object')

In [14]:
nbs_['caption']

5000    a woman in a blue jacket stands with a microph...
5001    an older man with white hair and a suit is see...
5002    a man in a suit stands in front of an american...
5003    a man in a blue suit stands in a room with a p...
5004    a man in a blue suit and red tie sits on a cha...
                              ...
6244    a black and white photo of a large assembly ha...
6245    an aerial view of a flooded road with a yellow...
6246    an individual stands in a barren landscape wit...
6247    a person in a fluffy red and white costume wit...
6248    an armored military vehicle with a mounted gun...
Name: caption, Length: 1249, dtype: object

In [15]:
nbs_nbs.columns

Index(['article_text', 'image_path', 'MultiModal_Label'], dtype='object')

In [16]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

NBS plus Model that is text + image

Defining the model

In [17]:

batch_size = 4 
epochs = 1
LEARNING_RATE = 3.2999999999999996e-05
fusion_type ='cosine_similarity'

In [18]:
class MultimodalClassifier(nn.Module):
    def __init__(
            self,
            text_encoder_id_or_path: str,
            image_encoder_id_or_path: str,
            projection_dim: int,
            fusion_method: Literal["concat", "align", "cosine_similarity"] = fusion_type,
            proj_dropout: float = 0.1,
            fusion_dropout: float = 0.1,
            num_classes: int = 2,
        ) -> None:
        super().__init__()

        self.fusion_method = fusion_method
        self.projection_dim = projection_dim
        self.num_classes = num_classes

        ##### Text Encoder
        self.text_encoder = BertModel.from_pretrained(text_encoder_id_or_path)
        self.text_projection = nn.Sequential(
            nn.Linear(self.text_encoder.config.hidden_size, self.projection_dim),
            nn.Dropout(proj_dropout),
        )

        ##### Image Encoder (using ResNet34 from AutoModel with timm)
        self.image_encoder = AutoModel.from_pretrained(image_encoder_id_or_path, trust_remote_code=True)
        self.image_encoder.classifier = nn.Identity()  # rm the classification head
        self.image_projection = nn.Sequential(
            nn.Linear(512, self.projection_dim),
            nn.Dropout(proj_dropout),
        )

        ##### Fusion Layer
        fusion_input_dim = self.projection_dim * 2 if fusion_method == "concat" else self.projection_dim
        self.fusion_layer = nn.Sequential(
            nn.Dropout(fusion_dropout),
            nn.Linear(fusion_input_dim, self.projection_dim),
            nn.GELU(),
            nn.Dropout(fusion_dropout),
        )

        ##### Classification Layer
        self.classifier = nn.Linear(self.projection_dim, self.num_classes)

    def forward(self, pixel_values: torch.Tensor, input_ids: torch.Tensor, attention_mask: torch.Tensor) -> torch.Tensor:
        ##### Text Encoder Projection #####
        full_text_features = self.text_encoder(input_ids=input_ids, attention_mask=attention_mask, return_dict=True).last_hidden_state
        full_text_features = full_text_features[:, 0, :]  # using cls token
        full_text_features = self.text_projection(full_text_features)

        ##### Image Encoder Projection #####
        resnet_image_features = self.image_encoder(pixel_values=pixel_values).last_hidden_state
        
        # global average pooling for resent image features (bad idea? dim problems)
        resnet_image_features = resnet_image_features.mean(dim=[-2, -1])
        resnet_image_features = self.image_projection(resnet_image_features)

        ##### Fusion and Classification #####
        if self.fusion_method == "concat":
            fused_features = torch.cat([full_text_features, resnet_image_features], dim=-1)
        else:
            fused_features = full_text_features * resnet_image_features # don't think this works atm (should be dot prod)

        # fusion and classifier layers
        fused_features = self.fusion_layer(fused_features)
        classification_output = self.classifier(fused_features)

        return classification_output

def load_model():
    config = {
        "model_type": "multimodal-bias-classifier", 
        "text_encoder_id_or_path": "E:\\GitHub\\Multi-Model-Bias-Detection-and-Debiasing-the-News\\EDA\\Model_config", 
        "image_encoder_id_or_path": "resnet34", 
        "projection_dim": 768, 
        "fusion_method": "concat", 
        "num_classes": 1, "proj_dropout": 0.1, 
        "fusion_dropout": 0.1, "hidden_size": 768, 
        "save_components": ["resnet_encoder", "text_encoder", "fusion_layer", "classifier"], 
        "exclude_components": ["clip_text_encoder", "clip_image_encoder"]}


    model = MultimodalClassifier(
        text_encoder_id_or_path=config["text_encoder_id_or_path"],
        image_encoder_id_or_path="microsoft/resnet-34",
        projection_dim=config["projection_dim"],
        fusion_method=config["fusion_method"],
        proj_dropout=config["proj_dropout"],
        fusion_dropout=config["fusion_dropout"],
        num_classes=config["num_classes"]
    )

    model_weights_path = hf_hub_download(repo_id="maximuspowers/multimodal-bias-classifier", filename="model_weights.pth")
    checkpoint = torch.load(model_weights_path, map_location=torch.device('cpu'))
    model.load_state_dict(checkpoint, strict=False)

    return model

Loading the saved model

In [19]:
dict=torch.load("fine_tuned_model_nbs.pt")
model_NBS = load_model()
model_NBS.load_state_dict(dict)
model_NBS.eval()

Some weights of BertModel were not initialized from the model checkpoint at E:\GitHub\Multi-Model-Bias-Detection-and-Debiasing-the-News\EDA\Model_config and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

MultimodalClassifier(
  (text_encoder): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-5): 6 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (text_projection): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): Dropout(p=0.1, inplace=False)
  )
  (image_encoder): ResNetModel(
    (embedder): ResNetEmbeddings(
      (embedder): ResNetConvLayer(
        (convolution): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
        (normalization): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (activation): ReLU()
      )
      (pooler): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    )
    (encoder): ResNetEncoder(
      (stages): ModuleList(
        (0): ResNetStage(
          (layers): Sequential(
            (0): ResNetBasicLayer(
              (shortcut): Identity()
              (layer): Sequential(
                (0): ResNetConvLayer(
                  (convolution): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): ReLU()
                )
                (1): ResNetConvLayer(
                  (convolution): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): Identity()
                )
              )
              (activation): ReLU()
            )
            (1): ResNetBasicLayer(
              (shortcut): Identity()
              (layer): Sequential(
                (0): ResNetConvLayer(
                  (convolution): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): ReLU()
                )
                (1): ResNetConvLayer(
                  (convolution): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): Identity()
                )
              )
              (activation): ReLU()
            )
            (2): ResNetBasicLayer(
              (shortcut): Identity()
              (layer): Sequential(
                (0): ResNetConvLayer(
                  (convolution): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): ReLU()
                )
                (1): ResNetConvLayer(
                  (convolution): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): Identity()
                )
              )
              (activation): ReLU()
            )
          )
        )
        (1): ResNetStage(
          (layers): Sequential(
            (0): ResNetBasicLayer(
              (shortcut): ResNetShortCut(
                (convolution): Conv2d(64, 128, kernel_size=(1, 1), stride=(2, 2), bias=False)
                (normalization): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              )
              (layer): Sequential(
                (0): ResNetConvLayer(
                  (convolution): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): ReLU()
                )
                (1): ResNetConvLayer(
                  (convolution): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): Identity()
                )
              )
              (activation): ReLU()
            )
            (1): ResNetBasicLayer(
              (shortcut): Identity()
              (layer): Sequential(
                (0): ResNetConvLayer(
                  (convolution): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): ReLU()
                )
                (1): ResNetConvLayer(
                  (convolution): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): Identity()
                )
              )
              (activation): ReLU()
            )
            (2): ResNetBasicLayer(
              (shortcut): Identity()
              (layer): Sequential(
                (0): ResNetConvLayer(
                  (convolution): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): ReLU()
                )
                (1): ResNetConvLayer(
                  (convolution): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): Identity()
                )
              )
              (activation): ReLU()
            )
            (3): ResNetBasicLayer(
              (shortcut): Identity()
              (layer): Sequential(
                (0): ResNetConvLayer(
                  (convolution): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): ReLU()
                )
                (1): ResNetConvLayer(
                  (convolution): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): Identity()
                )
              )
              (activation): ReLU()
            )
          )
        )
        (2): ResNetStage(
          (layers): Sequential(
            (0): ResNetBasicLayer(
              (shortcut): ResNetShortCut(
                (convolution): Conv2d(128, 256, kernel_size=(1, 1), stride=(2, 2), bias=False)
                (normalization): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              )
              (layer): Sequential(
                (0): ResNetConvLayer(
                  (convolution): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): ReLU()
                )
                (1): ResNetConvLayer(
                  (convolution): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): Identity()
                )
              )
              (activation): ReLU()
            )
            (1): ResNetBasicLayer(
              (shortcut): Identity()
              (layer): Sequential(
                (0): ResNetConvLayer(
                  (convolution): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): ReLU()
                )
                (1): ResNetConvLayer(
                  (convolution): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): Identity()
                )
              )
              (activation): ReLU()
            )
            (2): ResNetBasicLayer(
              (shortcut): Identity()
              (layer): Sequential(
                (0): ResNetConvLayer(
                  (convolution): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): ReLU()
                )
                (1): ResNetConvLayer(
                  (convolution): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): Identity()
                )
              )
              (activation): ReLU()
            )
            (3): ResNetBasicLayer(
              (shortcut): Identity()
              (layer): Sequential(
                (0): ResNetConvLayer(
                  (convolution): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): ReLU()
                )
                (1): ResNetConvLayer(
                  (convolution): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): Identity()
                )
              )
              (activation): ReLU()
            )
            (4): ResNetBasicLayer(
              (shortcut): Identity()
              (layer): Sequential(
                (0): ResNetConvLayer(
                  (convolution): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): ReLU()
                )
                (1): ResNetConvLayer(
                  (convolution): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): Identity()
                )
              )
              (activation): ReLU()
            )
            (5): ResNetBasicLayer(
              (shortcut): Identity()
              (layer): Sequential(
                (0): ResNetConvLayer(
                  (convolution): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): ReLU()
                )
                (1): ResNetConvLayer(
                  (convolution): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): Identity()
                )
              )
              (activation): ReLU()
            )
          )
        )
        (3): ResNetStage(
          (layers): Sequential(
            (0): ResNetBasicLayer(
              (shortcut): ResNetShortCut(
                (convolution): Conv2d(256, 512, kernel_size=(1, 1), stride=(2, 2), bias=False)
                (normalization): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
              )
              (layer): Sequential(
                (0): ResNetConvLayer(
                  (convolution): Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): ReLU()
                )
                (1): ResNetConvLayer(
                  (convolution): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): Identity()
                )
              )
              (activation): ReLU()
            )
            (1): ResNetBasicLayer(
              (shortcut): Identity()
              (layer): Sequential(
                (0): ResNetConvLayer(
                  (convolution): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): ReLU()
                )
                (1): ResNetConvLayer(
                  (convolution): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): Identity()
                )
              )
              (activation): ReLU()
            )
            (2): ResNetBasicLayer(
              (shortcut): Identity()
              (layer): Sequential(
                (0): ResNetConvLayer(
                  (convolution): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): ReLU()
                )
                (1): ResNetConvLayer(
                  (convolution): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
                  (normalization): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                  (activation): Identity()
                )
              )
              (activation): ReLU()
            )
          )
        )
      )
    )
    (pooler): AdaptiveAvgPool2d(output_size=(1, 1))
    (classifier): Identity()
  )
  (image_projection): Sequential(
    (0): Linear(in_features=512, out_features=768, bias=True)
    (1): Dropout(p=0.1, inplace=False)
  )
  (fusion_layer): Sequential(
    (0): Dropout(p=0.1, inplace=False)
    (1): Linear(in_features=1536, out_features=768, bias=True)
    (2): GELU(approximate='none')
    (3): Dropout(p=0.1, inplace=False)
  )
  (classifier): Linear(in_features=768, out_features=1, bias=True)
)

Text Based Model (BABE Model)

Defining the base Model

In [20]:
from transformers import BertModel

class BertClass(torch.nn.Module):
    def __init__(self):
        super(BertClass, self).__init__()
        self.l1 = BertModel.from_pretrained("E:\\GitHub\\Multi-Model-Bias-Detection-and-Debiasing-the-News\\EDA\\Model_config")
        self.pre_classifier = torch.nn.Linear(768, 768)
        self.dropout = torch.nn.Dropout(0.1)
        self.classifier = torch.nn.Linear(768, 2)
        self.relu = torch.nn.ReLU()

    def forward(self, input_ids, attention_mask, token_type_ids):
        output_1 = self.l1(input_ids=input_ids, attention_mask=attention_mask, token_type_ids=token_type_ids)
        hidden_state = output_1[0]
        pooler = hidden_state[:, 0]
        pooler = self.pre_classifier(pooler)
        pooler = self.relu(pooler)
        pooler = self.dropout(pooler)
        output = self.classifier(pooler)
        return output

Loading the pre trained weights

In [21]:
dict=torch.load("BABE_fine_tuned_model.pt")
model_BABE = BertClass()
model_BABE.load_state_dict(dict)
model_BABE.eval()

Some weights of BertModel were not initialized from the model checkpoint at E:\GitHub\Multi-Model-Bias-Detection-and-Debiasing-the-News\EDA\Model_config and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

BertClass(
  (l1): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-5): 6 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (relu): ReLU()
)

In [22]:
import torch
from transformers import AutoTokenizer
from PIL import Image
import requests
from torchvision import transforms

Tokenizer

In [23]:
text_tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
image_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])
MAX_LEN = 512

Babe Dataset Data Loader and Dataset

In [24]:
from torch.utils.data import Dataset, DataLoader
import torch
class Dataloader_Babe(Dataset):
    def __init__(self, dataframe, tokenizer, max_len):
        self.tokenizer = tokenizer
        self.text1 = dataframe['article'].values
        self.text2 = dataframe['text'].values
        self.targets = dataframe['label_bias'].values
        self.max_len = max_len

    def __len__(self):
        return len(self.text1)

    def __getitem__(self, index):
        text1 = str(self.text1[index])
        text2 = str(self.text2[index])

        inputs = self.tokenizer(

            text1,
            text2,
            add_special_tokens=True,
            max_length=self.max_len,
            padding='max_length',
            truncation=True,
            return_token_type_ids=True,
            return_attention_mask=True
        )
        ids = inputs['input_ids']
        mask = inputs['attention_mask']
        token_type_ids = inputs["token_type_ids"]


        return {
            'ids': torch.tensor(ids, dtype=torch.long),
            'mask': torch.tensor(mask, dtype=torch.long),
            'token_type_ids': torch.tensor(token_type_ids, dtype=torch.long),
            'targets': torch.tensor(self.targets[index], dtype=torch.float)
        }
    

def train_ldr_for_babe(X_train,batch_size=2):
    
    training_set = Dataloader_Babe(X_train, text_tokenizer, MAX_LEN)
    train_params = {'batch_size': batch_size,
                'shuffle': True,
                'num_workers': 0
                }
    
    training_loader = DataLoader(training_set, **train_params)
    return training_loader


def valid_ldr_for_babe(X_test,batch_size=2):
    
    valid_set = Dataloader_Babe(X_test, text_tokenizer, MAX_LEN)
    valid_params = {'batch_size': batch_size,
                'shuffle': True,
                'num_workers': 0
                }
    
    valid_loader = DataLoader(valid_set, **valid_params)
    return valid_loader

NBS Plus: Data Loader

In [25]:
nbs_nbs

,article_text,image_path,MultiModal_Label
5000,a woman in a blue jacket stands with a microph...,c:\users\ritik\downloads\images\images\18736ee...,0
5001,an older man with white hair and a suit is see...,c:\users\ritik\downloads\images\images\14c3316...,0
5002,a man in a suit stands in front of an american...,c:\users\ritik\downloads\images\images\16dacc5...,0
5003,a man in a blue suit stands in a room with a p...,c:\users\ritik\downloads\images\images\1b74984...,0
5004,a man in a blue suit and red tie sits on a cha...,c:\users\ritik\downloads\images\images\0753c02...,0
...,...,...,...
6244,a black and white photo of a large assembly ha...,c:\users\ritik\downloads\images\images\0471e10...,0
6245,an aerial view of a flooded road with a yellow...,c:\users\ritik\downloads\images\images\1e9e145...,0
6246,an individual stands in a barren landscape wit...,c:\users\ritik\downloads\images\images\0bc2d5d...,0
6247,a person in a fluffy red and white costume wit...,c:\users\ritik\downloads\images\images\1913a7c...,0
6248,an armored military vehicle with a mounted gun...,c:\users\ritik\downloads\images\images\075600b...,0

In [26]:
from torch.utils.data import Dataset, DataLoader
from PIL import Image

class Dataloader_NBS_Plus(Dataset):
    def __init__(self, dataframe, text_tokenizer, image_transform):
        self.df = dataframe
        self.text_tokenizer = text_tokenizer
        self.image_transform = image_transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        text = row['article_text']
        image_path = row['image_path']

        # tokenize text
        text_inputs = self.text_tokenizer(
            text, padding='max_length', truncation=True, max_length=512 , return_tensors='pt'
        )
        # transform image
        image = Image.open(image_path).convert('RGB')
        image_input = self.image_transform(image)

        #label = torch.tensor(row['MultiModal_Label'])
        
        input_ids= text_inputs['input_ids'][0]
        attention_mask= text_inputs['attention_mask']
        pixel_values = image_input
        labels =  int(row['MultiModal_Label'])
        return {
            'input_ids': torch.tensor(input_ids, dtype=torch.long),
            'attention_mask': torch.tensor(attention_mask, dtype=torch.long),
            'pixel_values': image_input,
            'labels': torch.tensor(labels, dtype=torch.long)
        }

def train_dataloader_nbs(dataset):
    
    train_loader_dataset = Dataloader_NBS_Plus(dataset, text_tokenizer, image_transform)
    training_loader = DataLoader(train_loader_dataset, batch_size=4, shuffle=True)

    return training_loader


def valid_dataloader_nbs(dataset):
    
    test_loader_dataset = Dataloader_NBS_Plus(dataset, text_tokenizer, image_transform)

    val_loader = DataLoader(test_loader_dataset, batch_size=4, shuffle=True)
    return val_loader

Validation of Babe

In [27]:
from tqdm import tqdm

loss_function = torch.nn.CrossEntropyLoss()



def valid_BABE(model, testing_loader):
    prob_all = []
    prob_target = []
    model.eval()
    with torch.no_grad():
        for _, data in tqdm(enumerate(testing_loader, 0)):
            ids = data['ids'].to(device, dtype = torch.long)
            mask = data['mask'].to(device, dtype = torch.long)
            token_type_ids = data['token_type_ids'].to(device, dtype=torch.long)
            targets = data['targets'].to(device, dtype = torch.long)
            outputs = model(ids, mask, token_type_ids)
            prob=torch.softmax(outputs, dim=1)
            prob_all.append(prob)
            prob_target.append(targets)
            
    prob_all = torch.cat(prob_all).numpy()       
    prob_target = torch.cat(prob_target).numpy()
    return prob_all,prob_target

Validation of NBS

In [28]:
def valid_NBS(model, testing_loader):
    model.eval()
    prob_all = []
    prob_target = []
    with torch.no_grad():
        for _, data in tqdm(enumerate(testing_loader, 0)):
            ids = data['input_ids'].to(device, dtype = torch.long)
            mask = data['attention_mask'].to(device, dtype = torch.long)
            pixel_values = data['pixel_values'].to(device, dtype = torch.float)
            targets = data['labels'].reshape(-1,1).to(device, dtype = torch.float)

            outputs = model(input_ids=ids,
            attention_mask=mask,
            pixel_values=pixel_values)

            preds = torch.sigmoid(outputs)     
            prob = torch.sigmoid(outputs)
            prob_all.append(prob)
            prob_target.append(targets)
            

    prob_all = torch.cat(prob_all).numpy()       
    prob_target = torch.cat(prob_target).numpy()
    return prob_all,prob_target

#https://stackoverflow.com/questions/62301674/extracting-labels-after-applying-softmax  --> For Probability, Weights and Labels

In [29]:
from hyperopt import hp

space = {
    'w': hp.uniform('w', 0,1)
}

In [30]:
nbs_

,unique_id,outlet_x,title,content,text_label_x,outlet_y,headline,top_image,article_text,new_categories,news_categories_confidence_scores,text_label_y,image_filename,image_path,text_labels,MultiModal_Label,caption
5000,18736eea37,newsweek,"nikki haley mocks donald trump, joe biden with...",newsweek/images/18736eea37.txt,likely,newsweek,"nikki haley mocks donald trump, joe biden with...","{'bytes': none, 'path': '/projects/nmb-plus/co...",republican presidential hopeful nikki haley to...,['politics' 'national'],[0.95 0.85],likely,18736eea37.jpg,c:\users\ritik\downloads\images\images\18736ee...,biased,0,a woman in a blue jacket stands with a microph...
5001,14c3316900,newsweek,democrat warns u.s. response to jordan attack ...,newsweek/images/14c3316900.txt,likely,newsweek,democrat warns u.s. response to jordan attack ...,"{'bytes': none, 'path': '/projects/nmb-plus/co...",senator tim kaine said in an interview with cn...,['politics' 'international'],[0.9 0.8],likely,14c3316900.jpg,c:\users\ritik\downloads\images\images\14c3316...,biased,0,an older man with white hair and a suit is see...
5002,16dacc5669,newsweek,democrat brutally mocked for video of him sing...,newsweek/images/16dacc5669.txt,likely,newsweek,democrat brutally mocked for video of him sing...,"{'bytes': none, 'path': '/projects/nmb-plus/co...",colorado governor jared polis has been critici...,['politics' 'local/regional'],[0.95 0.85],likely,16dacc5669.jpg,c:\users\ritik\downloads\images\images\16dacc5...,biased,0,a man in a suit stands in front of an american...
5003,1b749844c0,newsweek,michael cohen's big 2024 plans - newsweek,newsweek/images/1b749844c0.txt,likely,newsweek,michael cohen's big 2024 plans - newsweek,"{'bytes': none, 'path': '/projects/nmb-plus/co...",former trump fixer michael cohen has big plans...,['politics' 'national'],[0.95 0.75],likely,1b749844c0.jpg,c:\users\ritik\downloads\images\images\1b74984...,biased,0,a man in a blue suit stands in a room with a p...
5004,0753c02b4a,newsweek,conservative slams maga for 'actually evil' co...,newsweek/images/0753c02b4a.txt,likely,newsweek,conservative slams maga for 'actually evil' co...,"{'bytes': none, 'path': '/projects/nmb-plus/co...",a conservative slammed make america great agai...,['politics'],[0.95],likely,0753c02b4a.jpg,c:\users\ritik\downloads\images\images\0753c02...,biased,0,a man in a blue suit and red tie sits on a cha...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6244,0471e108dd,cnn,opinion: we germans are making trump ‘thunders...,editor’s note: anna sauerbrey is the foreign e...,likely,cnn,opinion: we germans are making trump ‘thunders...,"{'bytes': none, 'path': '/projects/nmb-plus/wh...",editors note anna sauerbrey is the foreign edi...,['opinion/editorial' 'politics'],[0.9 0.8],likely,0471e108dd.jpg,c:\users\ritik\downloads\images\images\0471e10...,biased,0,a black and white photo of a large assembly ha...
6245,1e9e145f6e,cnn,brazil’s floods smashed through barriers desig...,karine pitana had just paid off the last insta...,likely,cnn,brazil’s floods smashed through barriers desig...,"{'bytes': none, 'path': '/projects/nmb-plus/wh...",karine pitana had just paid off the last insta...,['local/regional' 'national'],[0.85 0.75],likely,1e9e145f6e.jpg,c:\users\ritik\downloads\images\images\1e9e145...,biased,0,an aerial view of a flooded road with a yellow...
6246,0bc2d5dd25,cnn,"in a city cut off from the world, guns and dru...",on the rare days that the hills surrounding po...,likely,cnn,"in a city cut off from the world, guns and dru...","{'bytes': none, 'path': '/projects/nmb-plus/wh...",on the rare days that the hills surrounding po...,['national' 'international'],[0.8 0.7],likely,0bc2d5dd25.jpg,c:\users\ritik\downloads\images\images\0bc2d5d...,biased,0,an individual stands in a barren landscape wit...
6247,1913a7c1b2,cnn,switzerland wins eurovision after politically ...,switzerland’s nemo won a chaotic and political...,likely,cnn,switzerland wins eurovision after politically ...,"{'bytes': none, 'path': '/projects/nmb-plus/wh...",switzerlands nemo won a chaotic and politicall...,['international' 'entertainment'],[0.85 0.8 ],likely,1913a7c1b2.jpg,c:\users\ritik\downloads\images\images\1913a7c...,biased,0,a person in a fluffy red and white costume wit...
6248,075600b516,cnn,"may 9, 2024 israel-hamas war - cnn",netanyahu says biden made a mistake in delayin...,likely,cnn,"may 9, 2024 israel-hamas war - cnn","{'bytes': none, 'path': '/projects/nmb-plus/wh...",netanyahu says biden made a mistake in delayin...,['politics' 'international'],[0.95 0.9 ],likely,075600b516.jpg,c:\users\ritik\downloads\images\images\075600b...,biased,0,an armored military vehicle with a mounted gun...

In [31]:
'''
nbs_probs,true = valid_NBS(model_NBS,valid_dataloader_nbs(nbs_nbs))
babe_probs,true_ = valid_BABE(model_BABE,valid_ldr_for_babe(nbs_babe))
'''

'\nnbs_probs,true = valid_NBS(model_NBS,valid_dataloader_nbs(nbs_nbs))\nbabe_probs,true_ = valid_BABE(model_BABE,valid_ldr_for_babe(nbs_babe))\n'

In [32]:
'''nbs_probs.shape'''

'nbs_probs.shape'

In [33]:
'''babe_probs.shape'''

'babe_probs.shape'

In [34]:
'''babe_probs'''

'babe_probs'

In [35]:
'''nbs_probs'''

'nbs_probs'

In [36]:
from sklearn.metrics import f1_score
from hyperopt import STATUS_OK, STATUS_FAIL

def obj_func(params):
    try:
        

        
        nbs_probs,true = valid_NBS(model_NBS,valid_dataloader_nbs(nbs_nbs))
        babe_probs,true_ = valid_BABE(model_BABE,valid_ldr_for_babe(nbs_babe))

        w = params['w']
        total_rpob = w*nbs_probs.reshape(-1) + (1-w)*babe_probs[:,1]
        pred = (total_rpob > 0.5).astype(int)
        f1 = f1_score(true, pred, average='weighted')

        return {'loss': -f1, 'status': STATUS_OK}
    except Exception as e:
        print("Exception:", e)
        return {'status': STATUS_FAIL}

In [ ]:
from hyperopt import fmin, tpe, Trials

trials = Trials()

best = fmin(
    fn=obj_func,
    space=space,
    algo=tpe.suggest,
    max_evals=4,
    trials=trials
)

print("Best hyperparameters:", best)

  0%|          | 0/4 [00:00<?, ?trial/s, best loss=?]

0it [00:00, ?it/s]
C:\Users\ritik\AppData\Local\Temp\ipykernel_11128\247880750.py:33: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(input_ids, dtype=torch.long),

C:\Users\ritik\AppData\Local\Temp\ipykernel_11128\247880750.py:34: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'attention_mask': torch.tensor(attention_mask, dtype=torch.long),

1it [00:01,  1.52s/it]
2it [00:02,  1.43s/it]
3it [00:04,  1.36s/it]
4it [00:05,  1.23s/it]
5it [00:06,  1.16s/it]
6it [00:07,  1.12s/it]
7it [00:08,  1.13s/it]
8it [00:09,  1.14s/it]
9it [00:10,  1.20s/it]
10it [00:12,  1.27s/it]
11it [00:13,  1.36s/it]
12it [00:15,  1.36s/it]
13it [00:16,  1.32s/it]
14it [00:17,  1.27s/it]
15it [00:19,  1.31s/it]
16it [00:20,  1.36s/it]
17it [00:21,  1.34s/it]
18it [00:23,  1.30s/it]
19it [00:24,  1.27s/it]
20it [00:25,  1.27s/it]
21it [00:26,  1.32s/it]
22it [00:27,  1.22s/it]
23it [00:29,  1.25s/it]
24it [00:30,  1.18s/it]
25it [00:31,  1.15s/it]
26it [00:32,  1.12s/it]
27it [00:33,  1.08s/it]
28it [00:34,  1.17s/it]
29it [00:35,  1.14s/it]
30it [00:37,  1.25s/it]
31it [00:38,  1.25s/it]
32it [00:39,  1.23s/it]
33it [00:41,  1.27s/it]
34it [00:42,  1.19s/it]
35it [00:43,  1.13s/it]
36it [00:44,  1.10s/it]
37it [00:45,  1.12s/it]
38it [00:46,  1.09s/it]
39it [00:47,  1.05s/it]
40it [00:48,  1.03s/it]
41it [00:49,  1.11s/it]
42it [00:50,  1.09s/it]
43it [00:51,  1.11s/it]
44it [00:52,  1.06s/it]
45it [00:53,  1.04s/it]
46it [00:54,  1.07s/it]
47it [00:56,  1.13s/it]
48it [00:57,  1.12s/it]
49it [00:58,  1.09s/it]
50it [00:59,  1.12s/it]
51it [01:00,  1.10s/it]
52it [01:01,  1.11s/it]
53it [01:02,  1.09s/it]
54it [01:04,  1.20s/it]
55it [01:05,  1.13s/it]
56it [01:06,  1.09s/it]
57it [01:07,  1.05s/it]
58it [01:08,  1.04s/it]
59it [01:09,  1.02s/it]
60it [01:10,  1.12s/it]
61it [01:11,  1.10s/it]
62it [01:12,  1.14s/it]
63it [01:13,  1.19s/it]
64it [01:15,  1.22s/it]
65it [01:16,  1.17s/it]
66it [01:17,  1.13s/it]
67it [01:18,  1.07s/it]
68it [01:19,  1.10s/it]
69it [01:20,  1.12s/it]
70it [01:21,  1.08s/it]
71it [01:22,  1.10s/it]
72it [01:23,  1.06s/it]
73it [01:24,  1.04s/it]
74it [01:25,  1.04s/it]
75it [01:26,  1.04s/it]
76it [01:27,  1.03s/it]
77it [01:28,  1.01s/it]
78it [01:29,  1.02s/it]
79it [01:30,  1.03s/it]
80it [01:31,  1.03s/it]
81it [01:32,  1.01s/it]
82it [01:33,  1.05s/it]
83it [01:35,  1.11s/it]
84it [01:36,  1.15s/it]
85it [01:37,  1.17s/it]
86it [01:38,  1.14s/it]
87it [01:39,  1.12s/it]
88it [01:41,  1.24s/it]
89it [01:42,  1.23s/it]
90it [01:44,  1.30s/it]
91it [01:45,  1.22s/it]
92it [01:46,  1.30s/it]
93it [01:47,  1.30s/it]
94it [01:49,  1.34s/it]
95it [01:50,  1.28s/it]
96it [01:52,  1.39s/it]
97it [01:53,  1.32s/it]
98it [01:55,  1.50s/it]
99it [01:56,  1.37s/it]
100it [01:57,  1.43s/it]
101it [01:59,  1.39s/it]
102it [02:00,  1.36s/it]
103it [02:01,  1.26s/it]
104it [02:02,  1.22s/it]
105it [02:03,  1.23s/it]
106it [02:04,  1.18s/it]
107it [02:06,  1.26s/it]
108it [02:07,  1.19s/it]
109it [02:08,  1.14s/it]
110it [02:09,  1.15s/it]
111it [02:10,  1.10s/it]
112it [02:11,  1.08s/it]
113it [02:12,  1.13s/it]
114it [02:14,  1.20s/it]
115it [02:15,  1.19s/it]
116it [02:16,  1.19s/it]
117it [02:17,  1.15s/it]
118it [02:18,  1.15s/it]
119it [02:19,  1.12s/it]
120it [02:20,  1.15s/it]
121it [02:22,  1.29s/it]
122it [02:23,  1.21s/it]
123it [02:24,  1.16s/it]
124it [02:25,  1.11s/it]
125it [02:26,  1.16s/it]
126it [02:27,  1.11s/it]
127it [02:28,  1.07s/it]
128it [02:30,  1.17s/it]
129it [02:31,  1.13s/it]
130it [02:32,  1.15s/it]
131it [02:33,  1.10s/it]
132it [02:34,  1.07s/it]
133it [02:35,  1.05s/it]
134it [02:36,  1.13s/it]
135it [02:38,  1.19s/it]
136it [02:39,  1.19s/it]
137it [02:40,  1.17s/it]
138it [02:41,  1.23s/it]
139it [02:43,  1.32s/it]
140it [02:44,  1.24s/it]
141it [02:45,  1.20s/it]
142it [02:46,  1.16s/it]
143it [02:47,  1.14s/it]
144it [02:49,  1.20s/it]
145it [02:50,  1.16s/it]
146it [02:51,  1.13s/it]
147it [02:52,  1.13s/it]
148it [02:53,  1.09s/it]
149it [02:54,  1.05s/it]
150it [02:55,  1.07s/it]
151it [02:56,  1.08s/it]
152it [02:57,  1.09s/it]
153it [02:58,  1.10s/it]
154it [02:59,  1.06s/it]
155it [03:00,  1.12s/it]
156it [03:01,  1.06s/it]
157it [03:02,  1.06s/it]
158it [03:04,  1.10s/it]
159it [03:05,  1.11s/it]
160it [03:06,  1.13s/it]
161it [03:08,  1.31s/it]
162it [03:09,  1.24s/it]
163it [03:10,  1.17s/it]
164it [03:11,  1.13s/it]
165it [03:12,  1.24s/it]
166it [03:14,  1.29s/it]
167it [03:15,  1.29s/it]
168it [03:16,  1.26s/it]
169it [03:17,  1.19s/it]
170it [03:18,  1.18s/it]
171it [03:19,  1.17s/it]
172it [03:20,  1.11s/it]
173it [03:22,  1.11s/it]
174it [03:23,  1.11s/it]
175it [03:24,  1.09s/it]
176it [03:25,  1.08s/it]
177it [03:26,  1.05s/it]
178it [03:27,  1.07s/it]
179it [03:28,  1.05s/it]
180it [03:29,  1.03s/it]
181it [03:30,  1.02s/it]
182it [03:31,  1.00it/s]
183it [03:32,  1.01it/s]
184it [03:33,  1.02s/it]
185it [03:34,  1.03s/it]
186it [03:35,  1.02s/it]
187it [03:36,  1.09s/it]
188it [03:37,  1.08s/it]
189it [03:38,  1.07s/it]
190it [03:39,  1.11s/it]
191it [03:40,  1.08s/it]
192it [03:41,  1.05s/it]
193it [03:43,  1.06s/it]
194it [03:44,  1.08s/it]
195it [03:45,  1.05s/it]
196it [03:46,  1.10s/it]
197it [03:47,  1.10s/it]
198it [03:48,  1.09s/it]
199it [03:49,  1.07s/it]
200it [03:50,  1.16s/it]
201it [03:52,  1.20s/it]
202it [03:53,  1.21s/it]
203it [03:54,  1.22s/it]
204it [03:55,  1.21s/it]
205it [03:57,  1.26s/it]
206it [03:58,  1.24s/it]
207it [03:59,  1.17s/it]
208it [04:00,  1.13s/it]
209it [04:01,  1.16s/it]
210it [04:03,  1.22s/it]
211it [04:04,  1.15s/it]
212it [04:05,  1.11s/it]
213it [04:06,  1.07s/it]
214it [04:07,  1.05s/it]
215it [04:08,  1.08s/it]
216it [04:09,  1.06s/it]
217it [04:10,  1.05s/it]
218it [04:11,  1.03s/it]
219it [04:12,  1.01s/it]
220it [04:13,  1.09s/it]
221it [04:14,  1.20s/it]
222it [04:15,  1.14s/it]
223it [04:16,  1.11s/it]
224it [04:18,  1.23s/it]
225it [04:19,  1.16s/it]
226it [04:20,  1.10s/it]
227it [04:21,  1.06s/it]
228it [04:22,  1.21s/it]
229it [04:24,  1.20s/it]
230it [04:25,  1.25s/it]
231it [04:26,  1.18s/it]
232it [04:27,  1.11s/it]
233it [04:28,  1.15s/it]
234it [04:29,  1.14s/it]
235it [04:30,  1.10s/it]
236it [04:31,  1.08s/it]
237it [04:33,  1.10s/it]
238it [04:34,  1.09s/it]
239it [04:35,  1.06s/it]
240it [04:36,  1.06s/it]
241it [04:37,  1.07s/it]
242it [04:38,  1.14s/it]
243it [04:39,  1.12s/it]
244it [04:40,  1.13s/it]
245it [04:41,  1.09s/it]
246it [04:43,  1.15s/it]
247it [04:44,  1.10s/it]
248it [04:45,  1.09s/it]
249it [04:46,  1.11s/it]
250it [04:47,  1.12s/it]
251it [04:48,  1.15s/it]
252it [04:49,  1.16s/it]
253it [04:50,  1.15s/it]
254it [04:51,  1.10s/it]
255it [04:53,  1.13s/it]
256it [04:54,  1.09s/it]
257it [04:55,  1.09s/it]
258it [04:56,  1.06s/it]
259it [04:57,  1.13s/it]
260it [04:58,  1.15s/it]
261it [04:59,  1.12s/it]
262it [05:00,  1.15s/it]
263it [05:02,  1.12s/it]
264it [05:03,  1.20s/it]
265it [05:04,  1.16s/it]
266it [05:06,  1.27s/it]
267it [05:07,  1.26s/it]
268it [05:08,  1.29s/it]
269it [05:09,  1.23s/it]
270it [05:10,  1.19s/it]
271it [05:11,  1.18s/it]
272it [05:12,  1.14s/it]
273it [05:14,  1.16s/it]
274it [05:15,  1.11s/it]
275it [05:16,  1.31s/it]
276it [05:17,  1.21s/it]
277it [05:18,  1.15s/it]
278it [05:19,  1.10s/it]
279it [05:20,  1.08s/it]
280it [05:22,  1.07s/it]
281it [05:23,  1.07s/it]
282it [05:24,  1.14s/it]
283it [05:25,  1.12s/it]
284it [05:26,  1.20s/it]
285it [05:27,  1.16s/it]
286it [05:28,  1.11s/it]
287it [05:29,  1.10s/it]
288it [05:30,  1.07s/it]
289it [05:32,  1.23s/it]
290it [05:33,  1.17s/it]
291it [05:34,  1.16s/it]
292it [05:36,  1.20s/it]
293it [05:37,  1.30s/it]
294it [05:38,  1.28s/it]
295it [05:39,  1.19s/it]
296it [05:41,  1.22s/it]
297it [05:42,  1.21s/it]
298it [05:43,  1.14s/it]
299it [05:44,  1.09s/it]
300it [05:45,  1.10s/it]
301it [05:46,  1.08s/it]
302it [05:47,  1.12s/it]
303it [05:48,  1.12s/it]
304it [05:49,  1.09s/it]
305it [05:50,  1.05s/it]
306it [05:51,  1.06s/it]
307it [05:52,  1.07s/it]
308it [05:53,  1.08s/it]
309it [05:55,  1.08s/it]
310it [05:55,  1.04s/it]
311it [05:56,  1.03s/it]
312it [05:57,  1.03s/it]
313it [05:58,  1.21it/s]
313it [05:58,  1.14s/it]
0it [00:00, ?it/s]
1it [00:00,  2.27it/s]
2it [00:00,  2.35it/s]
3it [00:01,  2.42it/s]
4it [00:01,  2.45it/s]
5it [00:02,  2.44it/s]
6it [00:02,  2.33it/s]
7it [00:02,  2.36it/s]
8it [00:03,  2.40it/s]
9it [00:03,  2.45it/s]
10it [00:04,  2.46it/s]
11it [00:04,  2.49it/s]
12it [00:04,  2.50it/s]
13it [00:05,  2.38it/s]
14it [00:05,  2.45it/s]
15it [00:06,  2.48it/s]
16it [00:06,  2.42it/s]
17it [00:07,  2.45it/s]
18it [00:07,  2.45it/s]
19it [00:07,  2.45it/s]
20it [00:08,  2.37it/s]
21it [00:08,  2.44it/s]
22it [00:09,  2.49it/s]
23it [00:09,  2.48it/s]
24it [00:09,  2.42it/s]
25it [00:10,  2.39it/s]
26it [00:10,  2.37it/s]
27it [00:11,  2.28it/s]
28it [00:11,  2.34it/s]
29it [00:12,  2.39it/s]
30it [00:12,  2.40it/s]
31it [00:12,  2.40it/s]
32it [00:13,  2.44it/s]
33it [00:13,  2.48it/s]
34it [00:14,  2.50it/s]
35it [00:14,  2.48it/s]
36it [00:14,  2.46it/s]
37it [00:15,  2.33it/s]
38it [00:15,  2.42it/s]
39it [00:16,  2.46it/s]
40it [00:16,  2.48it/s]
41it [00:16,  2.47it/s]
42it [00:17,  2.44it/s]
43it [00:17,  2.45it/s]
44it [00:18,  2.48it/s]
45it [00:18,  2.50it/s]
46it [00:18,  2.42it/s]
47it [00:19,  2.46it/s]
48it [00:19,  2.46it/s]
49it [00:20,  2.49it/s]
50it [00:20,  2.53it/s]
51it [00:20,  2.51it/s]
52it [00:21,  2.50it/s]
53it [00:21,  2.50it/s]
54it [00:22,  2.46it/s]
55it [00:22,  2.49it/s]
56it [00:22,  2.51it/s]
57it [00:23,  2.54it/s]
58it [00:23,  2.57it/s]
59it [00:24,  2.58it/s]
60it [00:24,  2.56it/s]
61it [00:24,  2.56it/s]
62it [00:25,  2.57it/s]
63it [00:25,  2.58it/s]
64it [00:26,  2.57it/s]
65it [00:26,  2.57it/s]
66it [00:26,  2.55it/s]
67it [00:27,  2.54it/s]
68it [00:27,  2.58it/s]
69it [00:27,  2.58it/s]
70it [00:28,  2.54it/s]
71it [00:28,  2.50it/s]
72it [00:29,  2.49it/s]
73it [00:29,  2.50it/s]
74it [00:30,  2.40it/s]
75it [00:30,  2.47it/s]
76it [00:30,  2.51it/s]
77it [00:31,  2.55it/s]
78it [00:31,  2.51it/s]
79it [00:31,  2.53it/s]
80it [00:32,  2.55it/s]
81it [00:32,  2.57it/s]
82it [00:33,  2.46it/s]
83it [00:33,  2.49it/s]
84it [00:34,  2.47it/s]
85it [00:34,  2.49it/s]
86it [00:34,  2.52it/s]
87it [00:35,  2.55it/s]
88it [00:35,  2.53it/s]
89it [00:35,  2.55it/s]
90it [00:36,  2.51it/s]
91it [00:36,  2.55it/s]
92it [00:37,  2.56it/s]
93it [00:37,  2.57it/s]
94it [00:37,  2.54it/s]
95it [00:38,  2.49it/s]
96it [00:38,  2.50it/s]
97it [00:39,  2.47it/s]
98it [00:39,  2.50it/s]
99it [00:39,  2.53it/s]
100it [00:40,  2.55it/s]
101it [00:40,  2.52it/s]
102it [00:41,  2.52it/s]
103it [00:41,  2.53it/s]
104it [00:41,  2.54it/s]
105it [00:42,  2.53it/s]
106it [00:42,  2.53it/s]
107it [00:43,  2.53it/s]
108it [00:43,  2.54it/s]
109it [00:43,  2.57it/s]
110it [00:44,  2.58it/s]
111it [00:44,  2.60it/s]
112it [00:45,  2.62it/s]
113it [00:45,  2.61it/s]
114it [00:45,  2.59it/s]
115it [00:46,  2.57it/s]
116it [00:46,  2.57it/s]
117it [00:46,  2.57it/s]
118it [00:47,  2.57it/s]
119it [00:47,  2.56it/s]
120it [00:48,  2.56it/s]
121it [00:48,  2.54it/s]
122it [00:48,  2.56it/s]
123it [00:49,  2.57it/s]
124it [00:49,  2.57it/s]
125it [00:50,  2.59it/s]
126it [00:50,  2.59it/s]
127it [00:50,  2.56it/s]
128it [00:51,  2.47it/s]
129it [00:51,  2.50it/s]
130it [00:52,  2.50it/s]
131it [00:52,  2.49it/s]
132it [00:52,  2.53it/s]
133it [00:53,  2.52it/s]
134it [00:53,  2.53it/s]
135it [00:54,  2.55it/s]
136it [00:54,  2.55it/s]
137it [00:54,  2.55it/s]
138it [00:55,  2.55it/s]
139it [00:55,  2.54it/s]
140it [00:56,  2.50it/s]
141it [00:56,  2.51it/s]
142it [00:56,  2.54it/s]
143it [00:57,  2.55it/s]
144it [00:57,  2.48it/s]
145it [00:58,  2.42it/s]
146it [00:58,  2.47it/s]
147it [00:58,  2.51it/s]
148it [00:59,  2.52it/s]
149it [00:59,  2.54it/s]
150it [01:00,  2.51it/s]
151it [01:00,  2.51it/s]
152it [01:00,  2.53it/s]
153it [01:01,  2.53it/s]
154it [01:01,  2.53it/s]
155it [01:01,  2.54it/s]
156it [01:02,  2.52it/s]
157it [01:02,  2.51it/s]
158it [01:03,  2.54it/s]
159it [01:03,  2.54it/s]
160it [01:03,  2.56it/s]
161it [01:04,  2.55it/s]
162it [01:04,  2.52it/s]
163it [01:05,  2.49it/s]
164it [01:05,  2.52it/s]
165it [01:05,  2.53it/s]
166it [01:06,  2.50it/s]
167it [01:06,  2.54it/s]
168it [01:07,  2.54it/s]
169it [01:07,  2.42it/s]
170it [01:07,  2.47it/s]
171it [01:08,  2.47it/s]
172it [01:08,  2.44it/s]
173it [01:09,  2.47it/s]
174it [01:09,  2.43it/s]
175it [01:10,  2.46it/s]
176it [01:10,  2.45it/s]
177it [01:10,  2.37it/s]
178it [01:11,  2.42it/s]
179it [01:11,  2.48it/s]
180it [01:12,  2.48it/s]
181it [01:12,  2.53it/s]
182it [01:12,  2.54it/s]
183it [01:13,  2.44it/s]
184it [01:13,  2.48it/s]
185it [01:14,  2.50it/s]
186it [01:14,  2.48it/s]
187it [01:14,  2.48it/s]
188it [01:15,  2.50it/s]
189it [01:15,  2.52it/s]
190it [01:16,  2.51it/s]
191it [01:16,  2.50it/s]
192it [01:16,  2.44it/s]
193it [01:17,  2.36it/s]
194it [01:17,  2.42it/s]
195it [01:18,  2.47it/s]
196it [01:18,  2.51it/s]
197it [01:18,  2.50it/s]
198it [01:19,  2.51it/s]
199it [01:19,  2.54it/s]
200it [01:20,  2.54it/s]
201it [01:20,  2.57it/s]
202it [01:20,  2.57it/s]
203it [01:21,  2.60it/s]
204it [01:21,  2.51it/s]
205it [01:22,  2.51it/s]
206it [01:22,  2.54it/s]
207it [01:22,  2.54it/s]
208it [01:23,  2.54it/s]
209it [01:23,  2.47it/s]
210it [01:24,  2.45it/s]
211it [01:24,  2.49it/s]
212it [01:24,  2.53it/s]
213it [01:25,  2.58it/s]
214it [01:25,  2.58it/s]
215it [01:26,  2.51it/s]
216it [01:26,  2.49it/s]
217it [01:26,  2.46it/s]
218it [01:27,  2.50it/s]
219it [01:27,  2.53it/s]
220it [01:28,  2.51it/s]
221it [01:28,  2.53it/s]
222it [01:28,  2.50it/s]
223it [01:29,  2.53it/s]
224it [01:29,  2.42it/s]
225it [01:30,  2.48it/s]
226it [01:30,  2.53it/s]
227it [01:30,  2.54it/s]
228it [01:31,  2.53it/s]
229it [01:31,  2.46it/s]
230it [01:32,  2.50it/s]
231it [01:32,  2.53it/s]
232it [01:32,  2.57it/s]
233it [01:33,  2.51it/s]
234it [01:33,  2.38it/s]
235it [01:34,  2.44it/s]
236it [01:34,  2.47it/s]
237it [01:34,  2.52it/s]
238it [01:35,  2.55it/s]
239it [01:35,  2.55it/s]
240it [01:36,  2.53it/s]
241it [01:36,  2.56it/s]
242it [01:36,  2.59it/s]
243it [01:37,  2.61it/s]
244it [01:37,  2.61it/s]
245it [01:37,  2.60it/s]
246it [01:38,  2.55it/s]
247it [01:38,  2.55it/s]
248it [01:39,  2.54it/s]
249it [01:39,  2.56it/s]
250it [01:39,  2.37it/s]
251it [01:40,  2.36it/s]
252it [01:40,  2.39it/s]
253it [01:41,  2.42it/s]
254it [01:41,  2.46it/s]
255it [01:41,  2.50it/s]
256it [01:42,  2.50it/s]
257it [01:42,  2.40it/s]
258it [01:43,  2.42it/s]
259it [01:43,  2.46it/s]
260it [01:44,  2.49it/s]
261it [01:44,  2.50it/s]
262it [01:44,  2.51it/s]
263it [01:45,  2.53it/s]
264it [01:45,  2.52it/s]
265it [01:45,  2.56it/s]
266it [01:46,  2.57it/s]
267it [01:46,  2.53it/s]
268it [01:47,  2.54it/s]
269it [01:47,  2.50it/s]
270it [01:48,  2.47it/s]
271it [01:48,  2.48it/s]
272it [01:48,  2.52it/s]
273it [01:49,  2.54it/s]
274it [01:49,  2.57it/s]
275it [01:49,  2.57it/s]
276it [01:50,  2.55it/s]
277it [01:50,  2.54it/s]
278it [01:51,  2.58it/s]
279it [01:51,  2.60it/s]
280it [01:51,  2.59it/s]
281it [01:52,  2.50it/s]
282it [01:52,  2.49it/s]
283it [01:53,  2.52it/s]
284it [01:53,  2.52it/s]
285it [01:53,  2.55it/s]
286it [01:54,  2.56it/s]
287it [01:54,  2.51it/s]
288it [01:55,  2.51it/s]
289it [01:55,  2.52it/s]
290it [01:55,  2.55it/s]
291it [01:56,  2.57it/s]
292it [01:56,  2.60it/s]
293it [01:56,  2.62it/s]
294it [01:57,  2.58it/s]
295it [01:57,  2.56it/s]
296it [01:58,  2.55it/s]
297it [01:58,  2.57it/s]
298it [01:58,  2.53it/s]
299it [01:59,  2.52it/s]
300it [01:59,  2.48it/s]
301it [02:00,  2.50it/s]
302it [02:00,  2.53it/s]
303it [02:00,  2.55it/s]
304it [02:01,  2.55it/s]
305it [02:01,  2.58it/s]
306it [02:02,  2.54it/s]
307it [02:02,  2.52it/s]
308it [02:02,  2.51it/s]
309it [02:03,  2.51it/s]
310it [02:03,  2.53it/s]
311it [02:04,  2.55it/s]
312it [02:04,  2.54it/s]
313it [02:04,  2.55it/s]
314it [02:05,  2.58it/s]
315it [02:05,  2.59it/s]
316it [02:06,  2.61it/s]
317it [02:06,  2.61it/s]
318it [02:06,  2.48it/s]
319it [02:07,  2.51it/s]
320it [02:07,  2.52it/s]
321it [02:08,  2.54it/s]
322it [02:08,  2.57it/s]
323it [02:08,  2.56it/s]
324it [02:09,  2.53it/s]
325it [02:09,  2.44it/s]
326it [02:10,  2.49it/s]
327it [02:10,  2.51it/s]
328it [02:10,  2.53it/s]
329it [02:11,  2.51it/s]
330it [02:11,  2.48it/s]
331it [02:12,  2.51it/s]
332it [02:12,  2.54it/s]
333it [02:12,  2.56it/s]
334it [02:13,  2.60it/s]
335it [02:13,  2.59it/s]
336it [02:13,  2.56it/s]
337it [02:14,  2.46it/s]
338it [02:14,  2.51it/s]
339it [02:15,  2.47it/s]
340it [02:15,  2.52it/s]
341it [02:15,  2.55it/s]
342it [02:16,  2.53it/s]
343it [02:16,  2.52it/s]
344it [02:17,  2.55it/s]
345it [02:17,  2.45it/s]
346it [02:17,  2.48it/s]
347it [02:18,  2.43it/s]
348it [02:18,  2.43it/s]
349it [02:19,  2.48it/s]
350it [02:19,  2.53it/s]
351it [02:19,  2.56it/s]
352it [02:20,  2.51it/s]
353it [02:20,  2.51it/s]
354it [02:21,  2.50it/s]
355it [02:21,  2.47it/s]
356it [02:21,  2.50it/s]
357it [02:22,  2.49it/s]
358it [02:22,  2.54it/s]
359it [02:23,  2.56it/s]
360it [02:23,  2.55it/s]
361it [02:23,  2.49it/s]
362it [02:24,  2.51it/s]
363it [02:24,  2.54it/s]
364it [02:25,  2.57it/s]
365it [02:25,  2.56it/s]
366it [02:25,  2.53it/s]
367it [02:26,  2.52it/s]
368it [02:26,  2.55it/s]
369it [02:27,  2.53it/s]
370it [02:27,  2.54it/s]
371it [02:27,  2.57it/s]
372it [02:28,  2.42it/s]
373it [02:28,  2.47it/s]
374it [02:29,  2.49it/s]
375it [02:29,  2.53it/s]
376it [02:29,  2.56it/s]
377it [02:30,  2.52it/s]
378it [02:30,  2.51it/s]
379it [02:31,  2.42it/s]
380it [02:31,  2.47it/s]
381it [02:31,  2.51it/s]
382it [02:32,  2.52it/s]
383it [02:32,  2.52it/s]
384it [02:33,  2.43it/s]
385it [02:33,  2.49it/s]
386it [02:33,  2.47it/s]
387it [02:34,  2.51it/s]
388it [02:34,  2.55it/s]
389it [02:35,  2.56it/s]
390it [02:35,  2.41it/s]
391it [02:35,  2.47it/s]
392it [02:36,  2.51it/s]
393it [02:36,  2.53it/s]
394it [02:37,  2.54it/s]
395it [02:37,  2.55it/s]
396it [02:37,  2.54it/s]
397it [02:38,  2.55it/s]
398it [02:38,  2.57it/s]
399it [02:39,  2.56it/s]
400it [02:39,  2.58it/s]
401it [02:39,  2.59it/s]
402it [02:40,  2.55it/s]
403it [02:40,  2.57it/s]
404it [02:40,  2.58it/s]
405it [02:41,  2.57it/s]
406it [02:41,  2.45it/s]
407it [02:42,  2.49it/s]
408it [02:42,  2.49it/s]
409it [02:42,  2.53it/s]
410it [02:43,  2.54it/s]
411it [02:43,  2.56it/s]
412it [02:44,  2.51it/s]
413it [02:44,  2.42it/s]
414it [02:45,  2.44it/s]
415it [02:45,  2.48it/s]
416it [02:45,  2.52it/s]
417it [02:46,  2.56it/s]
418it [02:46,  2.56it/s]
419it [02:46,  2.58it/s]
420it [02:47,  2.35it/s]
421it [02:47,  2.43it/s]
422it [02:48,  2.49it/s]
423it [02:48,  2.54it/s]
424it [02:48,  2.58it/s]
425it [02:49,  2.55it/s]
426it [02:49,  2.52it/s]
427it [02:50,  2.56it/s]
428it [02:50,  2.56it/s]
429it [02:50,  2.58it/s]
430it [02:51,  2.61it/s]
431it [02:51,  2.53it/s]
432it [02:52,  2.51it/s]
433it [02:52,  2.54it/s]
434it [02:52,  2.56it/s]
435it [02:53,  2.58it/s]
436it [02:53,  2.59it/s]
437it [02:54,  2.56it/s]
438it [02:54,  2.55it/s]
439it [02:54,  2.55it/s]
440it [02:55,  2.52it/s]
441it [02:55,  2.43it/s]
442it [02:56,  2.46it/s]
443it [02:56,  2.37it/s]
444it [02:56,  2.40it/s]
445it [02:57,  2.46it/s]
446it [02:57,  2.50it/s]
447it [02:58,  2.52it/s]
448it [02:58,  2.48it/s]
449it [02:58,  2.49it/s]
450it [02:59,  2.51it/s]
451it [02:59,  2.49it/s]
452it [03:00,  2.48it/s]
453it [03:00,  2.53it/s]
454it [03:00,  2.56it/s]
455it [03:01,  2.42it/s]
456it [03:01,  2.45it/s]
457it [03:02,  2.49it/s]
458it [03:02,  2.52it/s]
459it [03:02,  2.56it/s]
460it [03:03,  2.58it/s]
461it [03:03,  2.58it/s]
462it [03:04,  2.56it/s]
463it [03:04,  2.58it/s]
464it [03:04,  2.56it/s]
465it [03:05,  2.48it/s]
466it [03:05,  2.53it/s]

 25%|██▌       | 1/4 [10:07<30:22, 607.42s/trial, best loss: -0.33132932531730125]

0it [00:00, ?it/s]
C:\Users\ritik\AppData\Local\Temp\ipykernel_11128\247880750.py:33: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(input_ids, dtype=torch.long),

C:\Users\ritik\AppData\Local\Temp\ipykernel_11128\247880750.py:34: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'attention_mask': torch.tensor(attention_mask, dtype=torch.long),

1it [00:01,  1.31s/it]
2it [00:02,  1.11s/it]
3it [00:03,  1.10s/it]
4it [00:04,  1.07s/it]
5it [00:05,  1.18s/it]
6it [00:06,  1.10s/it]
7it [00:07,  1.04s/it]
8it [00:08,  1.13s/it]
9it [00:09,  1.09s/it]
10it [00:11,  1.11s/it]
11it [00:12,  1.07s/it]
12it [00:13,  1.08s/it]
13it [00:14,  1.09s/it]
14it [00:15,  1.04s/it]
15it [00:16,  1.01s/it]
16it [00:17,  1.02it/s]
17it [00:18,  1.00it/s]
18it [00:19,  1.00s/it]
19it [00:20,  1.08s/it]
20it [00:21,  1.06s/it]
21it [00:22,  1.08s/it]
22it [00:23,  1.13s/it]
23it [00:24,  1.06s/it]
24it [00:25,  1.02s/it]
25it [00:26,  1.03s/it]
26it [00:27,  1.02s/it]
27it [00:28,  1.07s/it]
28it [00:29,  1.02s/it]
29it [00:30,  1.03s/it]
30it [00:31,  1.04s/it]
31it [00:33,  1.18s/it]
32it [00:34,  1.10s/it]
33it [00:35,  1.05s/it]
34it [00:36,  1.03s/it]
35it [00:37,  1.01it/s]
36it [00:38,  1.01it/s]
37it [00:39,  1.01s/it]
38it [00:40,  1.00it/s]
39it [00:41,  1.01s/it]
40it [00:42,  1.01it/s]
41it [00:43,  1.00it/s]
42it [00:44,  1.02s/it]
43it [00:45,  1.08s/it]
44it [00:46,  1.04s/it]
45it [00:47,  1.05s/it]
46it [00:48,  1.13s/it]
47it [00:49,  1.06s/it]
48it [00:50,  1.04s/it]
49it [00:51,  1.02s/it]
50it [00:52,  1.08s/it]
51it [00:53,  1.03s/it]
52it [00:54,  1.04s/it]
53it [00:55,  1.03s/it]
54it [00:56,  1.00it/s]
55it [00:57,  1.00s/it]
56it [00:58,  1.05s/it]
57it [00:59,  1.02s/it]
58it [01:00,  1.05s/it]
59it [01:01,  1.02s/it]
60it [01:02,  1.01s/it]
61it [01:03,  1.00it/s]
62it [01:05,  1.07s/it]
63it [01:06,  1.02s/it]
64it [01:07,  1.11s/it]
65it [01:08,  1.04s/it]
66it [01:09,  1.03s/it]
67it [01:10,  1.00it/s]
68it [01:11,  1.03s/it]
69it [01:12,  1.01s/it]
70it [01:13,  1.03s/it]
71it [01:14,  1.03s/it]
72it [01:15,  1.01s/it]
73it [01:16,  1.05s/it]
74it [01:17,  1.05s/it]
75it [01:18,  1.04s/it]
76it [01:19,  1.03s/it]
77it [01:20,  1.00it/s]
78it [01:21,  1.01it/s]
79it [01:22,  1.04s/it]
80it [01:23,  1.10s/it]
81it [01:24,  1.05s/it]
82it [01:26,  1.17s/it]
83it [01:27,  1.09s/it]
84it [01:28,  1.06s/it]
85it [01:29,  1.06s/it]
86it [01:30,  1.12s/it]
87it [01:31,  1.13s/it]
88it [01:32,  1.07s/it]
89it [01:33,  1.05s/it]
90it [01:34,  1.01s/it]
91it [01:35,  1.02it/s]
92it [01:36,  1.00s/it]
93it [01:37,  1.10s/it]
94it [01:38,  1.08s/it]
95it [01:39,  1.06s/it]
96it [01:40,  1.06s/it]
97it [01:41,  1.04s/it]
98it [01:43,  1.13s/it]
99it [01:44,  1.14s/it]
100it [01:45,  1.10s/it]
101it [01:46,  1.14s/it]
102it [01:47,  1.12s/it]
103it [01:48,  1.12s/it]
104it [01:49,  1.06s/it]
105it [01:50,  1.04s/it]
106it [01:51,  1.09s/it]
107it [01:52,  1.06s/it]
108it [01:54,  1.11s/it]
109it [01:55,  1.12s/it]
110it [01:56,  1.08s/it]
111it [01:57,  1.07s/it]
112it [01:58,  1.03s/it]
113it [01:59,  1.02s/it]
114it [02:00,  1.00it/s]
115it [02:00,  1.03it/s]
116it [02:02,  1.06s/it]
117it [02:03,  1.08s/it]
118it [02:04,  1.04s/it]
119it [02:05,  1.03s/it]
120it [02:06,  1.02s/it]
121it [02:07,  1.00s/it]
122it [02:08,  1.00it/s]
123it [02:09,  1.05s/it]
124it [02:10,  1.01s/it]
125it [02:11,  1.01it/s]
126it [02:12,  1.02s/it]
127it [02:13,  1.02s/it]
128it [02:14,  1.06s/it]
129it [02:15,  1.16s/it]
130it [02:16,  1.10s/it]
131it [02:18,  1.12s/it]
132it [02:19,  1.06s/it]
133it [02:20,  1.08s/it]
134it [02:21,  1.03s/it]
135it [02:22,  1.02s/it]
136it [02:22,  1.01it/s]
137it [02:23,  1.03it/s]
138it [02:24,  1.06it/s]
139it [02:25,  1.02it/s]
140it [02:26,  1.01it/s]
141it [02:27,  1.01s/it]
142it [02:29,  1.20s/it]
143it [02:30,  1.13s/it]
144it [02:31,  1.15s/it]
145it [02:32,  1.07s/it]
146it [02:33,  1.10s/it]
147it [02:34,  1.09s/it]
148it [02:35,  1.08s/it]
149it [02:36,  1.06s/it]
150it [02:38,  1.09s/it]
151it [02:39,  1.11s/it]
152it [02:40,  1.11s/it]
153it [02:41,  1.13s/it]
154it [02:42,  1.12s/it]
155it [02:43,  1.09s/it]
156it [02:44,  1.05s/it]
157it [02:45,  1.05s/it]
158it [02:46,  1.04s/it]
159it [02:47,  1.03s/it]
160it [02:48,  1.01it/s]
161it [02:49,  1.03it/s]
162it [02:50,  1.02it/s]
163it [02:51,  1.00it/s]
164it [02:52,  1.01it/s]
165it [02:53,  1.03it/s]
166it [02:54,  1.01s/it]
167it [02:55,  1.01it/s]
168it [02:56,  1.04it/s]
169it [02:57,  1.08s/it]
170it [02:58,  1.08s/it]
171it [03:00,  1.15s/it]
172it [03:01,  1.08s/it]
173it [03:02,  1.18s/it]
174it [03:03,  1.12s/it]
175it [03:04,  1.17s/it]
176it [03:05,  1.17s/it]
177it [03:06,  1.10s/it]
178it [03:07,  1.06s/it]
179it [03:09,  1.12s/it]
180it [03:09,  1.05s/it]
181it [03:11,  1.17s/it]
182it [03:12,  1.21s/it]
183it [03:13,  1.15s/it]
184it [03:14,  1.07s/it]
185it [03:15,  1.06s/it]
186it [03:16,  1.05s/it]
187it [03:17,  1.09s/it]
188it [03:18,  1.04s/it]
189it [03:19,  1.02s/it]
190it [03:20,  1.01s/it]
191it [03:21,  1.00it/s]
192it [03:22,  1.07s/it]
193it [03:23,  1.03s/it]
194it [03:24,  1.01s/it]
195it [03:26,  1.10s/it]
196it [03:26,  1.04s/it]
197it [03:27,  1.00it/s]
198it [03:29,  1.13s/it]
199it [03:30,  1.14s/it]
200it [03:31,  1.07s/it]
201it [03:32,  1.03s/it]
202it [03:33,  1.05s/it]
203it [03:34,  1.02s/it]
204it [03:35,  1.01it/s]
205it [03:36,  1.01it/s]
206it [03:37,  1.02s/it]
207it [03:38,  1.01s/it]
208it [03:39,  1.07s/it]
209it [03:40,  1.02s/it]
210it [03:41,  1.01it/s]
211it [03:42,  1.06s/it]
212it [03:43,  1.03s/it]
213it [03:44,  1.06s/it]
214it [03:45,  1.02s/it]
215it [03:46,  1.01it/s]
216it [03:47,  1.03s/it]
217it [03:48,  1.02s/it]
218it [03:49,  1.03s/it]
219it [03:50,  1.05s/it]
220it [03:51,  1.02s/it]
221it [03:52,  1.01it/s]
222it [03:53,  1.04s/it]
223it [03:54,  1.06s/it]
224it [03:55,  1.02s/it]
225it [03:56,  1.02it/s]
226it [03:57,  1.02it/s]
227it [03:59,  1.07s/it]
228it [04:00,  1.05s/it]
229it [04:01,  1.03s/it]
230it [04:02,  1.08s/it]
231it [04:03,  1.04s/it]
232it [04:04,  1.08s/it]
233it [04:05,  1.05s/it]
234it [04:06,  1.02s/it]
235it [04:07,  1.01it/s]
236it [04:08,  1.03it/s]
237it [04:09,  1.03it/s]
238it [04:10,  1.03it/s]
239it [04:11,  1.10s/it]
240it [04:12,  1.06s/it]
241it [04:13,  1.03s/it]
242it [04:14,  1.09s/it]
243it [04:15,  1.05s/it]
244it [04:16,  1.02s/it]
245it [04:17,  1.01it/s]
246it [04:18,  1.02it/s]
247it [04:19,  1.02s/it]
248it [04:20,  1.01s/it]
249it [04:21,  1.00s/it]
250it [04:22,  1.02it/s]
251it [04:23,  1.15s/it]
252it [04:25,  1.17s/it]
253it [04:26,  1.09s/it]
254it [04:27,  1.04s/it]
255it [04:28,  1.04s/it]
256it [04:29,  1.11s/it]
257it [04:30,  1.07s/it]
258it [04:31,  1.02s/it]
259it [04:32,  1.03s/it]
260it [04:33,  1.01it/s]
261it [04:34,  1.00s/it]
262it [04:35,  1.03it/s]
263it [04:36,  1.03s/it]
264it [04:37,  1.00it/s]
265it [04:38,  1.03s/it]
266it [04:39,  1.02s/it]
267it [04:40,  1.01it/s]
268it [04:41,  1.03it/s]
269it [04:42,  1.00it/s]
270it [04:43,  1.03s/it]
271it [04:44,  1.01s/it]
272it [04:45,  1.04s/it]
273it [04:46,  1.06s/it]
274it [04:47,  1.06s/it]
275it [04:48,  1.03s/it]
276it [04:49,  1.00s/it]
277it [04:50,  1.01it/s]
278it [04:51,  1.02it/s]
279it [04:52,  1.03s/it]
280it [04:53,  1.07s/it]
281it [04:54,  1.05s/it]
282it [04:55,  1.07s/it]
283it [04:56,  1.04s/it]
284it [04:57,  1.02s/it]
285it [04:58,  1.03s/it]
286it [04:59,  1.01s/it]
287it [05:00,  1.01s/it]
288it [05:01,  1.02it/s]
289it [05:02,  1.05s/it]
290it [05:03,  1.01s/it]
291it [05:04,  1.00s/it]
292it [05:05,  1.01it/s]
293it [05:06,  1.03s/it]
294it [05:07,  1.01it/s]
295it [05:08,  1.02it/s]
296it [05:09,  1.03it/s]
297it [05:10,  1.04s/it]
298it [05:11,  1.06s/it]
299it [05:12,  1.03s/it]
300it [05:14,  1.14s/it]
301it [05:15,  1.11s/it]
302it [05:16,  1.08s/it]
303it [05:17,  1.08s/it]
304it [05:18,  1.03s/it]
305it [05:19,  1.02s/it]
306it [05:20,  1.01s/it]
307it [05:21,  1.02s/it]
308it [05:22,  1.03s/it]
309it [05:23,  1.00s/it]
310it [05:24,  1.00it/s]
311it [05:25,  1.03it/s]
312it [05:26,  1.02it/s]
313it [05:26,  1.31it/s]
313it [05:26,  1.04s/it]
0it [00:00, ?it/s]
1it [00:00,  2.65it/s]
2it [00:00,  2.44it/s]
3it [00:01,  2.31it/s]
4it [00:01,  2.41it/s]
5it [00:02,  2.49it/s]
6it [00:02,  2.51it/s]
7it [00:02,  2.55it/s]
8it [00:03,  2.41it/s]
9it [00:03,  2.46it/s]
10it [00:04,  2.37it/s]
11it [00:04,  2.45it/s]
12it [00:04,  2.49it/s]
13it [00:05,  2.49it/s]
14it [00:05,  2.48it/s]
15it [00:06,  2.51it/s]
16it [00:06,  2.55it/s]
17it [00:06,  2.54it/s]
18it [00:07,  2.58it/s]
19it [00:07,  2.60it/s]
20it [00:08,  2.57it/s]
21it [00:08,  2.54it/s]
22it [00:08,  2.56it/s]
23it [00:09,  2.45it/s]
24it [00:09,  2.49it/s]
25it [00:09,  2.54it/s]
26it [00:10,  2.54it/s]
27it [00:10,  2.49it/s]
28it [00:11,  2.52it/s]
29it [00:11,  2.56it/s]
30it [00:12,  2.49it/s]
31it [00:12,  2.47it/s]
32it [00:12,  2.46it/s]
33it [00:13,  2.52it/s]
34it [00:13,  2.53it/s]
35it [00:13,  2.55it/s]
36it [00:14,  2.54it/s]
37it [00:14,  2.42it/s]
38it [00:15,  2.45it/s]
39it [00:15,  2.49it/s]
40it [00:15,  2.54it/s]
41it [00:16,  2.55it/s]
42it [00:16,  2.53it/s]
43it [00:17,  2.54it/s]
44it [00:17,  2.55it/s]
45it [00:18,  2.44it/s]
46it [00:18,  2.49it/s]
47it [00:18,  2.51it/s]
48it [00:19,  2.53it/s]
49it [00:19,  2.55it/s]
50it [00:19,  2.55it/s]
51it [00:20,  2.59it/s]
52it [00:20,  2.61it/s]
53it [00:21,  2.61it/s]
54it [00:21,  2.62it/s]
55it [00:21,  2.61it/s]
56it [00:22,  2.60it/s]
57it [00:22,  2.60it/s]
58it [00:23,  2.61it/s]
59it [00:23,  2.60it/s]
60it [00:23,  2.62it/s]
61it [00:24,  2.59it/s]
62it [00:24,  2.58it/s]
63it [00:24,  2.59it/s]
64it [00:25,  2.58it/s]
65it [00:25,  2.59it/s]
66it [00:26,  2.57it/s]
67it [00:26,  2.58it/s]
68it [00:26,  2.57it/s]
69it [00:27,  2.56it/s]
70it [00:27,  2.56it/s]
71it [00:28,  2.59it/s]
72it [00:28,  2.47it/s]
73it [00:28,  2.39it/s]
74it [00:29,  2.42it/s]
75it [00:29,  2.48it/s]
76it [00:30,  2.52it/s]
77it [00:30,  2.55it/s]
78it [00:30,  2.58it/s]
79it [00:31,  2.57it/s]
80it [00:31,  2.57it/s]
81it [00:32,  2.58it/s]
82it [00:32,  2.58it/s]
83it [00:32,  2.56it/s]
84it [00:33,  2.57it/s]
85it [00:33,  2.59it/s]
86it [00:34,  2.51it/s]
87it [00:34,  2.52it/s]
88it [00:34,  2.36it/s]
89it [00:35,  2.43it/s]
90it [00:35,  2.47it/s]
91it [00:36,  2.52it/s]
92it [00:36,  2.53it/s]
93it [00:36,  2.54it/s]
94it [00:37,  2.56it/s]
95it [00:37,  2.54it/s]
96it [00:37,  2.55it/s]
97it [00:38,  2.56it/s]
98it [00:38,  2.53it/s]
99it [00:39,  2.55it/s]
100it [00:39,  2.56it/s]
101it [00:39,  2.57it/s]
102it [00:40,  2.57it/s]
103it [00:40,  2.57it/s]
104it [00:41,  2.56it/s]
105it [00:41,  2.58it/s]
106it [00:41,  2.60it/s]
107it [00:42,  2.61it/s]
108it [00:42,  2.61it/s]
109it [00:43,  2.56it/s]
110it [00:43,  2.55it/s]
111it [00:43,  2.57it/s]
112it [00:44,  2.47it/s]
113it [00:44,  2.51it/s]
114it [00:45,  2.56it/s]
115it [00:45,  2.57it/s]
116it [00:45,  2.56it/s]
117it [00:46,  2.58it/s]
118it [00:46,  2.43it/s]
119it [00:47,  2.49it/s]
120it [00:47,  2.51it/s]
121it [00:47,  2.48it/s]
122it [00:48,  2.51it/s]
123it [00:48,  2.49it/s]
124it [00:49,  2.51it/s]
125it [00:49,  2.44it/s]
126it [00:49,  2.49it/s]
127it [00:50,  2.33it/s]
128it [00:50,  2.39it/s]
129it [00:51,  2.46it/s]
130it [00:51,  2.49it/s]
131it [00:51,  2.49it/s]
132it [00:52,  2.50it/s]
133it [00:52,  2.51it/s]
134it [00:53,  2.54it/s]
135it [00:53,  2.56it/s]
136it [00:53,  2.56it/s]
137it [00:54,  2.57it/s]
138it [00:54,  2.60it/s]
139it [00:54,  2.60it/s]
140it [00:55,  2.59it/s]
141it [00:55,  2.51it/s]
142it [00:56,  2.54it/s]
143it [00:56,  2.44it/s]
144it [00:57,  2.39it/s]
145it [00:57,  2.43it/s]
146it [00:57,  2.48it/s]
147it [00:58,  2.53it/s]
148it [00:58,  2.51it/s]
149it [00:59,  2.54it/s]
150it [00:59,  2.56it/s]
151it [00:59,  2.53it/s]
152it [01:00,  2.54it/s]
153it [01:00,  2.57it/s]
154it [01:00,  2.56it/s]
155it [01:01,  2.57it/s]
156it [01:01,  2.59it/s]
157it [01:02,  2.58it/s]
158it [01:02,  2.59it/s]
159it [01:02,  2.58it/s]
160it [01:03,  2.58it/s]
161it [01:03,  2.59it/s]
162it [01:04,  2.58it/s]
163it [01:04,  2.58it/s]
164it [01:04,  2.60it/s]
165it [01:05,  2.60it/s]
166it [01:05,  2.62it/s]
167it [01:05,  2.61it/s]
168it [01:06,  2.61it/s]
169it [01:06,  2.62it/s]
170it [01:07,  2.62it/s]
171it [01:07,  2.61it/s]
172it [01:07,  2.60it/s]
173it [01:08,  2.61it/s]
174it [01:08,  2.61it/s]
175it [01:09,  2.59it/s]
176it [01:09,  2.57it/s]
177it [01:09,  2.57it/s]
178it [01:10,  2.57it/s]
179it [01:10,  2.44it/s]
180it [01:11,  2.38it/s]
181it [01:11,  2.37it/s]
182it [01:11,  2.40it/s]
183it [01:12,  2.46it/s]
184it [01:12,  2.50it/s]
185it [01:13,  2.54it/s]
186it [01:13,  2.55it/s]
187it [01:13,  2.56it/s]
188it [01:14,  2.56it/s]
189it [01:14,  2.58it/s]
190it [01:15,  2.57it/s]
191it [01:15,  2.56it/s]
192it [01:15,  2.56it/s]
193it [01:16,  2.58it/s]
194it [01:16,  2.59it/s]
195it [01:16,  2.54it/s]
196it [01:17,  2.58it/s]
197it [01:17,  2.59it/s]
198it [01:18,  2.60it/s]
199it [01:18,  2.54it/s]
200it [01:18,  2.53it/s]
201it [01:19,  2.53it/s]
202it [01:19,  2.55it/s]
203it [01:20,  2.51it/s]
204it [01:20,  2.53it/s]
205it [01:20,  2.54it/s]
206it [01:21,  2.55it/s]
207it [01:21,  2.58it/s]
208it [01:22,  2.60it/s]
209it [01:22,  2.59it/s]
210it [01:22,  2.49it/s]
211it [01:23,  2.52it/s]
212it [01:23,  2.56it/s]
213it [01:24,  2.58it/s]
214it [01:24,  2.56it/s]
215it [01:24,  2.59it/s]
216it [01:25,  2.59it/s]
217it [01:25,  2.57it/s]
218it [01:25,  2.55it/s]
219it [01:26,  2.57it/s]
220it [01:26,  2.55it/s]
221it [01:27,  2.58it/s]
222it [01:27,  2.60it/s]
223it [01:27,  2.60it/s]
224it [01:28,  2.60it/s]
225it [01:28,  2.51it/s]
226it [01:29,  2.53it/s]
227it [01:29,  2.56it/s]
228it [01:29,  2.59it/s]
229it [01:30,  2.57it/s]
230it [01:30,  2.56it/s]
231it [01:31,  2.58it/s]
232it [01:31,  2.57it/s]
233it [01:31,  2.56it/s]
234it [01:32,  2.54it/s]
235it [01:32,  2.53it/s]
236it [01:33,  2.51it/s]
237it [01:33,  2.50it/s]
238it [01:33,  2.53it/s]
239it [01:34,  2.53it/s]
240it [01:34,  2.54it/s]
241it [01:35,  2.52it/s]
242it [01:35,  2.47it/s]
243it [01:35,  2.49it/s]
244it [01:36,  2.52it/s]
245it [01:36,  2.55it/s]
246it [01:36,  2.57it/s]
247it [01:37,  2.57it/s]
248it [01:37,  2.53it/s]
249it [01:38,  2.56it/s]
250it [01:38,  2.58it/s]
251it [01:38,  2.60it/s]
252it [01:39,  2.61it/s]
253it [01:39,  2.60it/s]
254it [01:40,  2.58it/s]
255it [01:40,  2.52it/s]
256it [01:40,  2.40it/s]
257it [01:41,  2.48it/s]
258it [01:41,  2.52it/s]
259it [01:42,  2.53it/s]
260it [01:42,  2.55it/s]
261it [01:42,  2.56it/s]
262it [01:43,  2.57it/s]
263it [01:43,  2.51it/s]
264it [01:44,  2.54it/s]
265it [01:44,  2.56it/s]
266it [01:44,  2.57it/s]
267it [01:45,  2.58it/s]
268it [01:45,  2.60it/s]
269it [01:45,  2.59it/s]
270it [01:46,  2.58it/s]
271it [01:46,  2.44it/s]
272it [01:47,  2.41it/s]
273it [01:47,  2.46it/s]
274it [01:48,  2.50it/s]
275it [01:48,  2.50it/s]
276it [01:48,  2.52it/s]
277it [01:49,  2.55it/s]
278it [01:49,  2.56it/s]
279it [01:49,  2.55it/s]
280it [01:50,  2.56it/s]
281it [01:50,  2.55it/s]
282it [01:51,  2.54it/s]
283it [01:51,  2.56it/s]
284it [01:51,  2.56it/s]
285it [01:52,  2.59it/s]
286it [01:52,  2.60it/s]
287it [01:53,  2.61it/s]
288it [01:53,  2.60it/s]
289it [01:53,  2.60it/s]
290it [01:54,  2.59it/s]
291it [01:54,  2.58it/s]
292it [01:55,  2.59it/s]
293it [01:55,  2.61it/s]
294it [01:55,  2.60it/s]
295it [01:56,  2.53it/s]
296it [01:56,  2.44it/s]
297it [01:57,  2.36it/s]
298it [01:57,  2.42it/s]
299it [01:57,  2.48it/s]
300it [01:58,  2.49it/s]
301it [01:58,  2.54it/s]
302it [01:59,  2.54it/s]
303it [01:59,  2.57it/s]
304it [01:59,  2.48it/s]
305it [02:00,  2.50it/s]
306it [02:00,  2.54it/s]
307it [02:00,  2.56it/s]
308it [02:01,  2.55it/s]
309it [02:01,  2.55it/s]
310it [02:02,  2.59it/s]
311it [02:02,  2.58it/s]
312it [02:02,  2.61it/s]
313it [02:03,  2.62it/s]
314it [02:03,  2.49it/s]
315it [02:04,  2.47it/s]
316it [02:04,  2.50it/s]
317it [02:04,  2.52it/s]
318it [02:05,  2.56it/s]
319it [02:05,  2.54it/s]
320it [02:06,  2.52it/s]
321it [02:06,  2.53it/s]
322it [02:06,  2.55it/s]
323it [02:07,  2.55it/s]
324it [02:07,  2.55it/s]
325it [02:08,  2.50it/s]
326it [02:08,  2.48it/s]
327it [02:08,  2.49it/s]
328it [02:09,  2.51it/s]
329it [02:09,  2.50it/s]
330it [02:10,  2.52it/s]
331it [02:10,  2.54it/s]
332it [02:10,  2.53it/s]
333it [02:11,  2.55it/s]
334it [02:11,  2.53it/s]
335it [02:12,  2.54it/s]
336it [02:12,  2.54it/s]
337it [02:12,  2.55it/s]
338it [02:13,  2.54it/s]
339it [02:13,  2.42it/s]
340it [02:14,  2.46it/s]
341it [02:14,  2.41it/s]
342it [02:14,  2.45it/s]
343it [02:15,  2.47it/s]
344it [02:15,  2.48it/s]
345it [02:16,  2.46it/s]
346it [02:16,  2.49it/s]
347it [02:16,  2.52it/s]
348it [02:17,  2.54it/s]
349it [02:17,  2.55it/s]
350it [02:18,  2.53it/s]
351it [02:18,  2.54it/s]
352it [02:18,  2.55it/s]
353it [02:19,  2.56it/s]
354it [02:19,  2.56it/s]
355it [02:20,  2.58it/s]
356it [02:20,  2.54it/s]
357it [02:20,  2.54it/s]
358it [02:21,  2.54it/s]
359it [02:21,  2.54it/s]
360it [02:21,  2.56it/s]
361it [02:22,  2.57it/s]
362it [02:22,  2.56it/s]
363it [02:23,  2.52it/s]
364it [02:23,  2.52it/s]
365it [02:23,  2.49it/s]
366it [02:24,  2.34it/s]
367it [02:24,  2.39it/s]
368it [02:25,  2.45it/s]
369it [02:25,  2.47it/s]
370it [02:26,  2.50it/s]
371it [02:26,  2.53it/s]
372it [02:26,  2.54it/s]
373it [02:27,  2.55it/s]
374it [02:27,  2.52it/s]
375it [02:28,  2.52it/s]
376it [02:28,  2.54it/s]
377it [02:28,  2.56it/s]
378it [02:29,  2.58it/s]
379it [02:29,  2.48it/s]
380it [02:29,  2.50it/s]
381it [02:30,  2.52it/s]
382it [02:30,  2.54it/s]
383it [02:31,  2.55it/s]
384it [02:31,  2.57it/s]
385it [02:31,  2.57it/s]
386it [02:32,  2.57it/s]
387it [02:32,  2.57it/s]
388it [02:33,  2.59it/s]
389it [02:33,  2.58it/s]
390it [02:33,  2.57it/s]
391it [02:34,  2.45it/s]
392it [02:34,  2.49it/s]
393it [02:35,  2.51it/s]
394it [02:35,  2.53it/s]
395it [02:35,  2.57it/s]
396it [02:36,  2.58it/s]
397it [02:36,  2.57it/s]
398it [02:37,  2.59it/s]
399it [02:37,  2.58it/s]
400it [02:37,  2.56it/s]
401it [02:38,  2.58it/s]
402it [02:38,  2.59it/s]
403it [02:38,  2.60it/s]
404it [02:39,  2.61it/s]
405it [02:39,  2.57it/s]
406it [02:40,  2.57it/s]
407it [02:40,  2.59it/s]
408it [02:40,  2.60it/s]
409it [02:41,  2.59it/s]
410it [02:41,  2.56it/s]
411it [02:42,  2.49it/s]
412it [02:42,  2.51it/s]
413it [02:42,  2.54it/s]
414it [02:43,  2.52it/s]
415it [02:43,  2.55it/s]
416it [02:44,  2.57it/s]
417it [02:44,  2.55it/s]
418it [02:44,  2.57it/s]
419it [02:45,  2.60it/s]
420it [02:45,  2.62it/s]
421it [02:45,  2.59it/s]
422it [02:46,  2.58it/s]
423it [02:46,  2.57it/s]
424it [02:47,  2.60it/s]
425it [02:47,  2.62it/s]
426it [02:47,  2.62it/s]
427it [02:48,  2.62it/s]
428it [02:48,  2.63it/s]
429it [02:49,  2.61it/s]
430it [02:49,  2.59it/s]
431it [02:49,  2.59it/s]
432it [02:50,  2.61it/s]
433it [02:50,  2.63it/s]
434it [02:50,  2.62it/s]
435it [02:51,  2.58it/s]
436it [02:51,  2.55it/s]
437it [02:52,  2.57it/s]
438it [02:52,  2.59it/s]
439it [02:52,  2.59it/s]
440it [02:53,  2.61it/s]
441it [02:53,  2.60it/s]
442it [02:54,  2.55it/s]
443it [02:54,  2.56it/s]
444it [02:54,  2.55it/s]
445it [02:55,  2.45it/s]
446it [02:55,  2.50it/s]
447it [02:56,  2.53it/s]
448it [02:56,  2.52it/s]
449it [02:56,  2.54it/s]
450it [02:57,  2.54it/s]
451it [02:57,  2.56it/s]
452it [02:58,  2.54it/s]
453it [02:58,  2.57it/s]
454it [02:58,  2.57it/s]
455it [02:59,  2.55it/s]
456it [02:59,  2.55it/s]
457it [02:59,  2.56it/s]
458it [03:00,  2.44it/s]
459it [03:00,  2.41it/s]
460it [03:01,  2.43it/s]
461it [03:01,  2.49it/s]
462it [03:02,  2.52it/s]
463it [03:02,  2.55it/s]
464it [03:02,  2.53it/s]
465it [03:03,  2.52it/s]
466it [03:03,  2.52it/s]

 50%|█████     | 2/4 [19:40<19:33, 586.94s/trial, best loss: -0.33132932531730125]

0it [00:00, ?it/s]
C:\Users\ritik\AppData\Local\Temp\ipykernel_11128\247880750.py:33: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'input_ids': torch.tensor(input_ids, dtype=torch.long),

C:\Users\ritik\AppData\Local\Temp\ipykernel_11128\247880750.py:34: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  'attention_mask': torch.tensor(attention_mask, dtype=torch.long),

1it [00:00,  1.05it/s]
2it [00:01,  1.03it/s]
3it [00:03,  1.14s/it]
4it [00:04,  1.22s/it]
5it [00:05,  1.11s/it]
6it [00:06,  1.08s/it]
7it [00:07,  1.03s/it]
8it [00:08,  1.00s/it]
9it [00:09,  1.03s/it]
10it [00:10,  1.01s/it]
11it [00:11,  1.02s/it]
12it [00:12,  1.02s/it]
13it [00:13,  1.01it/s]
14it [00:14,  1.02s/it]
15it [00:15,  1.01it/s]
16it [00:16,  1.02it/s]
17it [00:17,  1.14s/it]
18it [00:19,  1.14s/it]
19it [00:20,  1.20s/it]
20it [00:21,  1.11s/it]
21it [00:22,  1.06s/it]
22it [00:23,  1.02s/it]
23it [00:24,  1.00it/s]
24it [00:25,  1.03it/s]
25it [00:26,  1.03it/s]
26it [00:27,  1.05s/it]
27it [00:28,  1.02s/it]
28it [00:29,  1.01it/s]
29it [00:29,  1.04it/s]
30it [00:31,  1.02s/it]
31it [00:32,  1.01s/it]
32it [00:33,  1.01s/it]
33it [00:34,  1.01it/s]
34it [00:35,  1.01it/s]
35it [00:36,  1.02it/s]
36it [00:37,  1.03it/s]
37it [00:37,  1.04it/s]
38it [00:38,  1.04it/s]
39it [00:39,  1.03it/s]
40it [00:40,  1.02it/s]
41it [00:41,  1.04it/s]
42it [00:42,  1.04it/s]
43it [00:43,  1.06it/s]
44it [00:44,  1.03it/s]
45it [00:45,  1.01s/it]
46it [00:47,  1.08s/it]
47it [00:48,  1.07s/it]
48it [00:49,  1.04s/it]
49it [00:49,  1.00s/it]
50it [00:51,  1.03s/it]
51it [00:52,  1.05s/it]
52it [00:53,  1.01s/it]
53it [00:54,  1.03s/it]
54it [00:55,  1.12s/it]
55it [00:56,  1.11s/it]
56it [00:57,  1.07s/it]
57it [00:58,  1.14s/it]
58it [00:59,  1.13s/it]
59it [01:01,  1.17s/it]
60it [01:02,  1.15s/it]
61it [01:03,  1.09s/it]
62it [01:04,  1.05s/it]
63it [01:05,  1.01s/it]
64it [01:06,  1.03it/s]
65it [01:07,  1.01s/it]
66it [01:08,  1.09s/it]
67it [01:09,  1.07s/it]
68it [01:10,  1.14s/it]
69it [01:11,  1.07s/it]
70it [01:12,  1.10s/it]
71it [01:13,  1.07s/it]
72it [01:14,  1.02s/it]
73it [01:15,  1.02s/it]
74it [01:16,  1.01it/s]
75it [01:17,  1.07s/it]
76it [01:18,  1.03s/it]
77it [01:19,  1.01it/s]
78it [01:20,  1.03it/s]
79it [01:21,  1.03s/it]
80it [01:22,  1.01it/s]
81it [01:23,  1.01s/it]
82it [01:24,  1.01it/s]
83it [01:26,  1.08s/it]
84it [01:27,  1.05s/it]
85it [01:28,  1.07s/it]
86it [01:29,  1.05s/it]
87it [01:30,  1.01s/it]
88it [01:31,  1.06s/it]
89it [01:32,  1.03s/it]
90it [01:33,  1.01it/s]
91it [01:34,  1.02it/s]
92it [01:35,  1.03it/s]
93it [01:35,  1.04it/s]
94it [01:36,  1.02it/s]
95it [01:38,  1.08s/it]
96it [01:39,  1.05s/it]
97it [01:40,  1.04s/it]
98it [01:41,  1.01s/it]
99it [01:42,  1.03it/s]
100it [01:43,  1.04it/s]
101it [01:44,  1.08s/it]
102it [01:45,  1.11s/it]
103it [01:46,  1.06s/it]
104it [01:47,  1.05s/it]
105it [01:48,  1.05s/it]
106it [01:49,  1.01s/it]
107it [01:50,  1.02it/s]
108it [01:51,  1.04it/s]
109it [01:52,  1.05it/s]
110it [01:53,  1.07it/s]
111it [01:54,  1.06it/s]
112it [01:55,  1.07it/s]
113it [01:56,  1.03it/s]
114it [01:57,  1.04s/it]
115it [01:58,  1.04s/it]
116it [01:59,  1.02s/it]
117it [02:00,  1.01it/s]
118it [02:01,  1.03it/s]
119it [02:02,  1.01it/s]
120it [02:03,  1.03it/s]
121it [02:04,  1.05it/s]
122it [02:04,  1.07it/s]
123it [02:05,  1.05it/s]
124it [02:07,  1.01s/it]
125it [02:07,  1.02it/s]
126it [02:09,  1.02s/it]
127it [02:10,  1.06s/it]
128it [02:11,  1.00s/it]
129it [02:12,  1.02s/it]
130it [02:13,  1.02s/it]
131it [02:14,  1.09s/it]
132it [02:15,  1.10s/it]
133it [02:16,  1.06s/it]
134it [02:17,  1.03s/it]
135it [02:18,  1.00s/it]
136it [02:19,  1.02s/it]
137it [02:20,  1.01it/s]
138it [02:21,  1.01it/s]
139it [02:22,  1.01it/s]
140it [02:23,  1.03it/s]
141it [02:24,  1.02it/s]
142it [02:25,  1.04it/s]
143it [02:26,  1.06it/s]
144it [02:27,  1.07it/s]
145it [02:27,  1.08it/s]
146it [02:28,  1.08it/s]
147it [02:29,  1.08it/s]
148it [02:31,  1.11s/it]
149it [02:32,  1.05s/it]
150it [02:33,  1.06s/it]
151it [02:34,  1.08s/it]
152it [02:35,  1.09s/it]
153it [02:36,  1.03s/it]
154it [02:37,  1.11s/it]
155it [02:38,  1.07s/it]
156it [02:39,  1.02s/it]
157it [02:40,  1.01s/it]
158it [02:41,  1.08s/it]
159it [02:43,  1.16s/it]
160it [02:44,  1.09s/it]
161it [02:45,  1.06s/it]
162it [02:46,  1.09s/it]
163it [02:47,  1.08s/it]
164it [02:48,  1.03s/it]
165it [02:49,  1.03s/it]
166it [02:50,  1.02s/it]
167it [02:51,  1.02s/it]
168it [02:52,  1.04s/it]
169it [02:53,  1.02s/it]
170it [02:54,  1.02s/it]
171it [02:55,  1.00s/it]
172it [02:56,  1.00s/it]
173it [02:57,  1.13s/it]
174it [02:58,  1.14s/it]
175it [02:59,  1.08s/it]
176it [03:00,  1.03s/it]
177it [03:02,  1.11s/it]
178it [03:02,  1.05s/it]
179it [03:04,  1.18s/it]
180it [03:05,  1.17s/it]
181it [03:06,  1.12s/it]
182it [03:07,  1.06s/it]
183it [03:08,  1.16s/it]
184it [03:09,  1.09s/it]
185it [03:11,  1.13s/it]
186it [03:12,  1.08s/it]
187it [03:13,  1.07s/it]
188it [03:14,  1.13s/it]
189it [03:15,  1.14s/it]
190it [03:16,  1.14s/it]
191it [03:17,  1.07s/it]
192it [03:18,  1.02s/it]
193it [03:19,  1.07s/it]
194it [03:20,  1.05s/it]
195it [03:21,  1.01s/it]
196it [03:22,  1.03s/it]
197it [03:23,  1.01s/it]
198it [03:24,  1.01it/s]
199it [03:25,  1.02it/s]
200it [03:26,  1.03it/s]
201it [03:27,  1.01it/s]
202it [03:29,  1.17s/it]
203it [03:30,  1.22s/it]
204it [03:31,  1.28s/it]
205it [03:32,  1.20s/it]
206it [03:33,  1.14s/it]
207it [03:34,  1.13s/it]
208it [34:55, 565.04s/it]
209it [34:56, 395.86s/it]
210it [35:00, 278.29s/it]
211it [35:02, 195.19s/it]
212it [35:03, 137.03s/it]
213it [35:04, 96.33s/it]
214it [35:06, 67.80s/it]
215it [35:07, 47.94s/it]
216it [35:08, 33.95s/it]
217it [35:10, 24.09s/it]
218it [35:11, 17.23s/it]
219it [35:12, 12.35s/it]
220it [35:13,  8.96s/it]
221it [35:14,  6.63s/it]
222it [35:15,  4.94s/it]
223it [35:16,  3.77s/it]
224it [35:17,  2.95s/it]
225it [35:18,  2.37s/it]
226it [35:19,  2.00s/it]
227it [35:20,  1.72s/it]
228it [35:22,  1.58s/it]
229it [35:23,  1.61s/it]
230it [35:25,  1.72s/it]
231it [35:26,  1.56s/it]
232it [35:27,  1.41s/it]
233it [35:29,  1.44s/it]
234it [35:31,  1.60s/it]
235it [35:32,  1.52s/it]
236it [35:34,  1.45s/it]
237it [35:35,  1.32s/it]
238it [35:36,  1.24s/it]
239it [35:37,  1.15s/it]
240it [35:38,  1.11s/it]
241it [35:39,  1.08s/it]
242it [35:39,  1.02s/it]
243it [35:41,  1.06s/it]
244it [35:42,  1.03s/it]
245it [35:43,  1.01s/it]
246it [35:43,  1.02it/s]
247it [35:44,  1.04it/s]
248it [35:45,  1.07it/s]
249it [35:46,  1.08it/s]
250it [35:47,  1.09it/s]
251it [35:48,  1.04it/s]
252it [35:49,  1.02it/s]
253it [35:51,  1.18s/it]
254it [35:52,  1.31s/it]
255it [35:54,  1.31s/it]
256it [35:55,  1.24s/it]
257it [35:56,  1.29s/it]
258it [35:57,  1.21s/it]
259it [35:58,  1.17s/it]
260it [35:59,  1.12s/it]
261it [36:01,  1.19s/it]
262it [36:02,  1.24s/it]
263it [36:03,  1.28s/it]
264it [36:05,  1.29s/it]
265it [36:06,  1.24s/it]
266it [36:07,  1.18s/it]
267it [36:08,  1.15s/it]
268it [36:09,  1.18s/it]
269it [36:10,  1.22s/it]
270it [36:12,  1.22s/it]
271it [36:13,  1.17s/it]
272it [36:14,  1.19s/it]
273it [36:15,  1.15s/it]
274it [36:16,  1.22s/it]
275it [36:17,  1.17s/it]
276it [36:19,  1.15s/it]
277it [36:20,  1.21s/it]
278it [36:21,  1.21s/it]
279it [36:22,  1.19s/it]
280it [36:23,  1.16s/it]
281it [36:25,  1.16s/it]
282it [36:26,  1.13s/it]
283it [36:27,  1.10s/it]
284it [36:28,  1.18s/it]
285it [36:29,  1.18s/it]

In [ ]:
class EnsembleModel(torch.nn.Module):
    def __init__(self,model_text_only,model_txt_and_img,valid_for_text,valid_for_imgandtxt,valid_loader_txt,valid_loader_textAndImage,w):
        super().__init__()
        ## Model Initialization
        self.model_text_only = model_text_only
        self.model_txt_and_img = model_txt_and_img

        #Parameter W for Fusion
        self.w = w

        #Dataloaders
        self.valid_loader_textAndImage = valid_loader_textAndImage
        self.valid_loader_txt = valid_loader_txt

        self.valid_for_text = valid_for_text
        self.valid_for_imgandtxt = valid_for_imgandtxt



    def forward(self,input_text,input_img_and_txt):
        probs_text,true = self.valid_for_text(self.model_text_only,self.valid_loader_txt(input_text))
        probs_textAndImage,true_ = self.valid_for_imgandtxt(self.model_txt_and_img,self.valid_loader_textAndImage(input_img_and_txt))
        total_rpob = self.w*probs_textAndImage.reshape(-1) + (1-self.w)*probs_text[:,1]
        pred = (total_rpob > 0.5).astype(int)

        return pred,true

: